package service

import (
	"context"
	"encoding/json"
	"net"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	appcookies "xiadown/internal/application/cookies"
	"xiadown/internal/domain/appsessions"
)

type CookiesExportFormat string

const (
	CookiesExportTXT  CookiesExportFormat = "txt"
	CookiesExportJSON CookiesExportFormat = "json"
)

func (service *AppSessionsService) ExportAppSessionCookies(ctx context.Context, id string, format CookiesExportFormat) (string, error) {
	session, err := service.sessionByID(ctx, id)
	if err != nil {
		return "", err
	}
	records, err := service.RecordsForSiteKey(ctx, session.SiteKey)
	if err != nil {
		return "", err
	}
	if len(records) == 0 {
		return "", appsessions.ErrNoCookies
	}
	return writeCookiesExport(records, format)
}

func writeCookiesExport(records []appcookies.Record, format CookiesExportFormat) (string, error) {
	ext := strings.ToLower(strings.TrimSpace(string(format)))
	if ext == "" {
		ext = string(CookiesExportTXT)
	}
	if ext != string(CookiesExportTXT) && ext != string(CookiesExportJSON) {
		return "", appsessions.ErrInvalidSession
	}
	file, err := os.CreateTemp("", "xiadown-cookies-*."+ext)
	if err != nil {
		return "", err
	}
	path := file.Name()
	if err := file.Close(); err != nil {
		return "", err
	}
	if ext == string(CookiesExportJSON) {
		if err := writeJSONCookies(path, records); err != nil {
			return "", err
		}
	} else {
		if err := writeNetscapeCookies(path, records); err != nil {
			return "", err
		}
	}
	return path, nil
}

func writeJSONCookies(path string, cookies []appcookies.Record) error {
	data, err := json.MarshalIndent(cookies, "", "  ")
	if err != nil {
		return err
	}
	return writeFileAtomic(path, data, 0o600)
}

func writeNetscapeCookies(path string, cookies []appcookies.Record) error {
	builder := strings.Builder{}
	builder.WriteString("# Netscape HTTP Cookie File\n")
	builder.WriteString("# This file was generated by XiaDown.\n")

	for _, cookie := range cookies {
		domain := strings.TrimSpace(cookie.Domain)
		if domain == "" {
			continue
		}
		secure := "FALSE"
		if cookie.Secure {
			secure = "TRUE"
		}
		pathValue := cookie.Path
		if strings.TrimSpace(pathValue) == "" {
			pathValue = "/"
		}
		expires := "0"
		if cookie.Expires > 0 {
			expires = strconv.FormatInt(cookie.Expires, 10)
		}
		for _, domainEntry := range netscapeCookieDomains(domain) {
			builder.WriteString(strings.Join([]string{
				domainEntry.domain,
				domainEntry.includeSubdomains,
				pathValue,
				secure,
				expires,
				cookie.Name,
				cookie.Value,
			}, "\t"))
			builder.WriteString("\n")
		}
	}

	return writeFileAtomic(path, []byte(builder.String()), 0o600)
}

type netscapeCookieDomain struct {
	domain            string
	includeSubdomains string
}

func netscapeCookieDomains(domain string) []netscapeCookieDomain {
	trimmed := strings.TrimSpace(domain)
	if trimmed == "" {
		return nil
	}
	if strings.HasPrefix(trimmed, ".") {
		return []netscapeCookieDomain{{
			domain:            trimmed,
			includeSubdomains: "TRUE",
		}}
	}
	domains := []netscapeCookieDomain{{
		domain:            trimmed,
		includeSubdomains: "FALSE",
	}}
	if canNetscapeCookieDomainIncludeSubdomains(trimmed) {
		domains = append(domains, netscapeCookieDomain{
			domain:            "." + trimmed,
			includeSubdomains: "TRUE",
		})
	}
	return domains
}

func canNetscapeCookieDomainIncludeSubdomains(domain string) bool {
	normalized := strings.Trim(strings.TrimSpace(domain), "[]")
	if normalized == "" || strings.Contains(normalized, ":") || !strings.Contains(normalized, ".") {
		return false
	}
	return net.ParseIP(normalized) == nil
}

func writeFileAtomic(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	tmp := filepath.Join(dir, "."+filepath.Base(path)+".tmp")
	if err := os.WriteFile(tmp, data, perm); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}
