import type { LibraryDTO, LibraryFileDTO } from "@/shared/contracts/library";
import { normalizeLanguage, t, type SupportedLanguage } from "@/shared/i18n";
import { buildAssetPreviewURL } from "@/shared/utils/resourceHelpers";

export {
  XIA_DEFAULT_THEME_PACK_ID,
  XIA_THEME_PACKS,
  mergeXiaAppearanceConfig,
  readXiaAppearance,
  resolveThemePack,
} from "@/shared/styles/xiadown-theme";
export type {
  XiaAccentMode,
  XiaAppearanceSettings,
  XiaSidebarStyle,
  XiaThemePack,
  XiaThemePackId,
} from "@/shared/styles/xiadown-theme";


function buildText(language: SupportedLanguage) {
  return {
    locale: language,
    appName: t("xiadown.appName", language),
    productSubtitle: t("xiadown.productSubtitle", language),
    website: t("xiadown.website", language),
    themePacks: {
      graphite: {
        label: t("xiadown.themePacks.graphite.label", language),
        description: t("xiadown.themePacks.graphite.description", language),
      },
      citrus: {
        label: t("xiadown.themePacks.citrus.label", language),
        description: t("xiadown.themePacks.citrus.description", language),
      },
      pixel: {
        label: t("xiadown.themePacks.pixel.label", language),
        description: t("xiadown.themePacks.pixel.description", language),
      },
      tape: {
        label: t("xiadown.themePacks.tape.label", language),
        description: t("xiadown.themePacks.tape.description", language),
      },
      teal: {
        label: t("xiadown.themePacks.teal.label", language),
        description: t("xiadown.themePacks.teal.description", language),
      },
      cloud: {
        label: t("xiadown.themePacks.cloud.label", language),
        description: t("xiadown.themePacks.cloud.description", language),
      },
      damson: {
        label: t("xiadown.themePacks.damson.label", language),
        description: t("xiadown.themePacks.damson.description", language),
      },
      fuchsia: {
        label: t("xiadown.themePacks.fuchsia.label", language),
        description: t("xiadown.themePacks.fuchsia.description", language),
      },
      cobalt: {
        label: t("xiadown.themePacks.cobalt.label", language),
        description: t("xiadown.themePacks.cobalt.description", language),
      },
      terracotta: {
        label: t("xiadown.themePacks.terracotta.label", language),
        description: t("xiadown.themePacks.terracotta.description", language),
      },
      lavender: {
        label: t("xiadown.themePacks.lavender.label", language),
        description: t("xiadown.themePacks.lavender.description", language),
      },
      nocturne: {
        label: t("xiadown.themePacks.nocturne.label", language),
        description: t("xiadown.themePacks.nocturne.description", language),
      },
    },
    library: {
      status: {
        queued: t("library.status.queued", language),
        running: t("library.status.running", language),
        succeeded: t("library.status.succeeded", language),
        failed: t("library.status.failed", language),
        canceled: t("library.status.canceled", language),
      },
      progress: {
        starting: t("library.progress.starting", language),
        preparing: t("library.progress.preparing", language),
        fetchingMetadata: t("library.progress.fetchingMetadata", language),
        transcoding: t("library.progress.transcoding", language),
        downloading: t("library.progress.downloading", language),
        downloadingVideo: t("library.progress.downloadingVideo", language),
        downloadingAudio: t("library.progress.downloadingAudio", language),
        downloadingSubtitles: t("library.progress.downloadingSubtitles", language),
        downloadingThumbnail: t("library.progress.downloadingThumbnail", language),
        muxing: t("library.progress.muxing", language),
        cleaningUp: t("library.progress.cleaningUp", language),
        postProcessing: t("library.progress.postProcessing", language),
      },
      progressDetail: {
        preparingDownload: t("library.progressDetail.preparingDownload", language),
        checkingDownloadTool: t(
          "library.progressDetail.checkingDownloadTool",
          language,
        ),
        preparingOutput: t("library.progressDetail.preparingOutput", language),
        exportingCookies: t("library.progressDetail.exportingCookies", language),
        checkingStreamManifest: t(
          "library.progressDetail.checkingStreamManifest",
          language,
        ),
        checkingMediaPlaylist: t(
          "library.progressDetail.checkingMediaPlaylist",
          language,
        ),
        checkingStreamKey: t(
          "library.progressDetail.checkingStreamKey",
          language,
        ),
        startingYtdlp: t("library.progressDetail.startingYtdlp", language),
        ytdlpDownloadingWebpage: t(
          "library.progressDetail.ytdlpDownloadingWebpage",
          language,
        ),
        ytdlpDownloadingApi: t(
          "library.progressDetail.ytdlpDownloadingApi",
          language,
        ),
        ytdlpDownloadingStreamInfo: t(
          "library.progressDetail.ytdlpDownloadingStreamInfo",
          language,
        ),
        ytdlpDownloadingDashManifest: t(
          "library.progressDetail.ytdlpDownloadingDashManifest",
          language,
        ),
        downloadingFragments: t(
          "library.progressDetail.downloadingFragments",
          language,
        ),
        muxingFormats: t("library.progressDetail.muxingFormats", language),
        postProcessingOutput: t(
          "library.progressDetail.postProcessingOutput",
          language,
        ),
        preparingFfmpegTranscode: t(
          "library.progressDetail.preparingFfmpegTranscode",
          language,
        ),
        ffmpegRenderingOutput: t(
          "library.progressDetail.ffmpegRenderingOutput",
          language,
        ),
        ffmpegTranscodeQueued: t(
          "library.progressDetail.ffmpegTranscodeQueued",
          language,
        ),
        ffmpegTranscodeCompleted: t(
          "library.progressDetail.ffmpegTranscodeCompleted",
          language,
        ),
        resumeRequested: t("library.progressDetail.resumeRequested", language),
        downloadCanceled: t("library.progressDetail.downloadCanceled", language),
        transcodeCanceled: t(
          "library.progressDetail.transcodeCanceled",
          language,
        ),
        operationCanceled: t(
          "library.progressDetail.operationCanceled",
          language,
        ),
        operationInterrupted: t(
          "library.progressDetail.operationInterrupted",
          language,
        ),
        downloadFailed: t("library.progressDetail.downloadFailed", language),
        transcodeFailed: t("library.progressDetail.transcodeFailed", language),
        operationFailed: t("library.progressDetail.operationFailed", language),
      },
    },
    views: {
      running: t("xiadown.views.running", language),
      completed: t("xiadown.views.completed", language),
      listen: t("xiadown.views.listen", language),
      connections: t("xiadown.views.connections", language),
      sniffDesk: t("xiadown.views.sniffDesk", language),
      tasks: t("xiadown.views.tasks", language),
      library: t("xiadown.views.library", language),
      files: t("xiadown.views.files", language),
    },
    actions: {
      settings: t("xiadown.actions.settings", language),
      open: t("xiadown.actions.open", language),
      close: t("xiadown.actions.close", language),
      closeBrowser: t("xiadown.actions.closeBrowser", language),
      clear: t("xiadown.actions.clear", language),
      cancel: t("xiadown.actions.cancel", language),
      cancelDialog: t("xiadown.actions.cancelDialog", language),
      resume: t("xiadown.actions.resume", language),
      view: t("xiadown.actions.view", language),
      delete: t("xiadown.actions.delete", language),
      deleteItem: t("xiadown.actions.deleteItem", language),
      start: t("xiadown.actions.start", language),
      startTask: t("xiadown.actions.startTask", language),
      addToDownloadQueue: t("xiadown.actions.addToDownloadQueue", language),
      next: t("xiadown.actions.next", language),
      back: t("xiadown.actions.back", language),
      installAll: t("xiadown.actions.installAll", language),
      download: t("xiadown.actions.download", language),
      transcode: t("xiadown.actions.transcode", language),
      analyze: t("xiadown.actions.analyze", language),
      createTask: t("xiadown.actions.createTask", language),
      chooseFile: t("xiadown.actions.chooseFile", language),
      chooseFolder: t("xiadown.actions.chooseFolder", language),
      reset: t("xiadown.actions.reset", language),
      save: t("xiadown.actions.save", language),
      install: t("xiadown.actions.install", language),
      verify: t("xiadown.actions.verify", language),
      testProxy: t("xiadown.actions.testProxy", language),
      openDirectory: t("xiadown.actions.openDirectory", language),
      checkUpdates: t("xiadown.actions.checkUpdates", language),
      installUpdate: t("xiadown.actions.installUpdate", language),
      restartToApply: t("xiadown.actions.restartToApply", language),
      previous: t("xiadown.actions.previous", language),
      nextTrack: t("xiadown.actions.nextTrack", language),
      pause: t("xiadown.actions.pause", language),
      play: t("xiadown.actions.play", language),
      openLogs: t("xiadown.actions.openLogs", language),
    },
    sidebar: {
      newTask: t("xiadown.sidebar.newTask", language),
      newDownload: t("xiadown.sidebar.newDownload", language),
      newTranscode: t("xiadown.sidebar.newTranscode", language),
      profileHint: t("xiadown.sidebar.profileHint", language),
      openDownloads: t("xiadown.sidebar.openDownloads", language),
      documentation: t("xiadown.sidebar.documentation", language),
      appUpdate: t("xiadown.sidebar.appUpdate", language),
      dependencyUpdate: t("xiadown.sidebar.dependencyUpdate", language),
    },
    petGallery: {
      title: t("xiadown.petGallery.title", language),
      breadcrumb: t("xiadown.petGallery.breadcrumb", language),
      gallery: t("xiadown.petGallery.gallery", language),
      localPets: t("xiadown.petGallery.localPets", language),
      detail: t("xiadown.petGallery.detail", language),
      empty: t("xiadown.petGallery.empty", language),
      showMore: t("xiadown.petGallery.showMore", language),
      importAction: t("xiadown.petGallery.importAction", language),
      importTitle: t("xiadown.petGallery.importTitle", language),
      importFailedTitle: t("xiadown.petGallery.importFailedTitle", language),
      importInvalid: t("xiadown.petGallery.importInvalid", language),
      importSucceeded: t("xiadown.petGallery.importSucceeded", language),
      petPackageFilter: t("xiadown.petGallery.petPackageFilter", language),
      errors: {
        packagePathRequired: t("xiadown.petGallery.errors.packagePathRequired", language),
        packageUnsupportedType: t("xiadown.petGallery.errors.packageUnsupportedType", language),
        packageReadFailed: t("xiadown.petGallery.errors.packageReadFailed", language),
        packageTooLarge: t("xiadown.petGallery.errors.packageTooLarge", language),
        packageOpenFailed: t("xiadown.petGallery.errors.packageOpenFailed", language),
        missingManifest: t("xiadown.petGallery.errors.missingManifest", language),
        missingSpritesheet: t("xiadown.petGallery.errors.missingSpritesheet", language),
        packageContentsTooLarge: t("xiadown.petGallery.errors.packageContentsTooLarge", language),
        archiveFileOpenFailed: t("xiadown.petGallery.errors.archiveFileOpenFailed", language),
        archiveFileReadFailed: t("xiadown.petGallery.errors.archiveFileReadFailed", language),
        manifestDecodeFailed: t("xiadown.petGallery.errors.manifestDecodeFailed", language),
        spritesheetDecodeFailed: t("xiadown.petGallery.errors.spritesheetDecodeFailed", language),
        spritesheetSizeInvalid: t("xiadown.petGallery.errors.spritesheetSizeInvalid", language),
        onlineDownloadCanceled: t("xiadown.petGallery.errors.onlineDownloadCanceled", language),
        onlineSessionRequired: t("xiadown.petGallery.errors.onlineSessionRequired", language),
        onlineSessionNotFound: t("xiadown.petGallery.errors.onlineSessionNotFound", language),
        onlineUnsupportedSite: t("xiadown.petGallery.errors.onlineUnsupportedSite", language),
      },
      exportTitle: t("xiadown.petGallery.exportTitle", language),
      exportAction: t("xiadown.petGallery.exportAction", language),
      exportSucceeded: t("xiadown.petGallery.exportSucceeded", language),
      deleteAction: t("xiadown.petGallery.deleteAction", language),
      deleteTitle: t("xiadown.petGallery.deleteTitle", language),
      deleteMessage: t("xiadown.petGallery.deleteMessage", language),
      deleteSucceeded: t("xiadown.petGallery.deleteSucceeded", language),
      activePet: t("xiadown.petGallery.activePet", language),
      setActive: t("xiadown.petGallery.setActive", language),
      loadingManifest: t("xiadown.petGallery.loadingManifest", language),
      scopeLabel: t("xiadown.petGallery.scopeLabel", language),
      sizeLabel: t("xiadown.petGallery.sizeLabel", language),
      gridLabel: t("xiadown.petGallery.gridLabel", language),
      cellLabel: t("xiadown.petGallery.cellLabel", language),
      previewAnimation: t("xiadown.petGallery.previewAnimation", language),
      scopes: {
        builtin: t("xiadown.petGallery.scopes.builtin", language),
        imported: t("xiadown.petGallery.scopes.imported", language),
      },
      origins: {
        localImport: t("xiadown.petGallery.origins.localImport", language),
        codexPetsNet: t("xiadown.petGallery.origins.codexPetsNet", language),
        codexpetXyz: t("xiadown.petGallery.origins.codexpetXyz", language),
        petdexDev: t("xiadown.petGallery.origins.petdexDev", language),
      },
      animations: {
        idle: t("xiadown.petGallery.animations.idle", language),
        "running-right": t("xiadown.petGallery.animations.runningRight", language),
        "running-left": t("xiadown.petGallery.animations.runningLeft", language),
        waving: t("xiadown.petGallery.animations.waving", language),
        jumping: t("xiadown.petGallery.animations.jumping", language),
        failed: t("xiadown.petGallery.animations.failed", language),
        waiting: t("xiadown.petGallery.animations.waiting", language),
        running: t("xiadown.petGallery.animations.running", language),
        review: t("xiadown.petGallery.animations.review", language),
      },
      generationGuide: {
        action: t("xiadown.petGallery.generationGuide.action", language),
        title: t("xiadown.petGallery.generationGuide.title", language),
        steps: [
          {
            title: t("xiadown.petGallery.generationGuide.steps.0.title", language),
            description: t("xiadown.petGallery.generationGuide.steps.0.description", language),
          },
          {
            title: t("xiadown.petGallery.generationGuide.steps.1.title", language),
            description: t("xiadown.petGallery.generationGuide.steps.1.description", language),
          },
          {
            title: t("xiadown.petGallery.generationGuide.steps.2.title", language),
            description: t("xiadown.petGallery.generationGuide.steps.2.description", language),
          },
          {
            title: t("xiadown.petGallery.generationGuide.steps.3.title", language),
            description: t("xiadown.petGallery.generationGuide.steps.3.description", language),
          },
        ],
        greatPetTitle: t("xiadown.petGallery.generationGuide.greatPetTitle", language),
        greatPetTips: [
          t("xiadown.petGallery.generationGuide.greatPetTips.0", language),
          t("xiadown.petGallery.generationGuide.greatPetTips.1", language),
          t("xiadown.petGallery.generationGuide.greatPetTips.2", language),
          t("xiadown.petGallery.generationGuide.greatPetTips.3", language),
        ],
      },
      importDialog: {
        description: t("xiadown.petGallery.importDialog.description", language),
        online: t("xiadown.petGallery.importDialog.online", language),
        local: t("xiadown.petGallery.importDialog.local", language),
        onlineDescription: t("xiadown.petGallery.importDialog.onlineDescription", language),
        onlineSite: t("xiadown.petGallery.importDialog.onlineSite", language),
        browse: t("xiadown.petGallery.importDialog.browse", language),
        browserStatus: t("xiadown.petGallery.importDialog.browserStatus", language),
        fileName: t("xiadown.petGallery.importDialog.fileName", language),
        path: t("xiadown.petGallery.importDialog.path", language),
        petName: t("xiadown.petGallery.importDialog.petName", language),
        validationReady: t("xiadown.petGallery.importDialog.validationReady", language),
        importSelected: t("xiadown.petGallery.importDialog.importSelected", language),
        importedPets: t("xiadown.petGallery.importDialog.importedPets", language),
        importedCount: t("xiadown.petGallery.importDialog.importedCount", language),
        importedEmpty: t("xiadown.petGallery.importDialog.importedEmpty", language),
        finish: t("xiadown.petGallery.importDialog.finish", language),
        sites: {
          codexPetsNet: t("xiadown.petGallery.importDialog.sites.codexPetsNet", language),
          codexpetXyz: t("xiadown.petGallery.importDialog.sites.codexpetXyz", language),
          petdexDev: t("xiadown.petGallery.importDialog.sites.petdexDev", language),
        },
        browserStatuses: {
          notOpen: t("xiadown.petGallery.importDialog.browserStatuses.notOpen", language),
          opening: t("xiadown.petGallery.importDialog.browserStatuses.opening", language),
          open: t("xiadown.petGallery.importDialog.browserStatuses.open", language),
          browserClosed: t("xiadown.petGallery.importDialog.browserStatuses.browserClosed", language),
          completed: t("xiadown.petGallery.importDialog.browserStatuses.completed", language),
          failed: t("xiadown.petGallery.importDialog.browserStatuses.failed", language),
        },
      },
    },
    sniffDesk: {
      title: t("xiadown.sniffDesk.title", language),
      sessions: t("xiadown.sniffDesk.sessions", language),
      resources: t("xiadown.sniffDesk.resources", language),
      startPlaceholder: t("xiadown.sniffDesk.startPlaceholder", language),
      startSniff: t("xiadown.sniffDesk.startSniff", language),
      startFailed: t("xiadown.sniffDesk.startFailed", language),
      urlRequired: t("xiadown.sniffDesk.urlRequired", language),
      urlInvalid: t("xiadown.sniffDesk.urlInvalid", language),
      urlUnsupported: t("xiadown.sniffDesk.urlUnsupported", language),
      urlUnsupportedDomain: t("xiadown.sniffDesk.urlUnsupportedDomain", language),
      searchPlaceholder: t("xiadown.sniffDesk.searchPlaceholder", language),
      kindFilter: t("xiadown.sniffDesk.kindFilter", language),
      sourceFilter: t("xiadown.sniffDesk.sourceFilter", language),
      downloadFilter: t("xiadown.sniffDesk.downloadFilter", language),
      allKinds: t("xiadown.sniffDesk.allKinds", language),
      allSources: t("xiadown.sniffDesk.allSources", language),
      allDownloads: t("xiadown.sniffDesk.allDownloads", language),
      downloadableOnly: t("xiadown.sniffDesk.downloadableOnly", language),
      emptySessions: t("xiadown.sniffDesk.emptySessions", language),
      emptyResources: t("xiadown.sniffDesk.emptyResources", language),
      emptyFilteredResources: t("xiadown.sniffDesk.emptyFilteredResources", language),
      loading: t("xiadown.sniffDesk.loading", language),
      currentPage: t("xiadown.sniffDesk.currentPage", language),
      tabCount: t("xiadown.sniffDesk.tabCount", language),
      resourceCount: t("xiadown.sniffDesk.resourceCount", language),
      updatedAt: t("xiadown.sniffDesk.updatedAt", language),
      statusOpen: t("xiadown.sniffDesk.statusOpen", language),
      statusClosing: t("xiadown.sniffDesk.statusClosing", language),
      statusTabClosed: t("xiadown.sniffDesk.statusTabClosed", language),
      statusClosed: t("xiadown.sniffDesk.statusClosed", language),
      sourceNetwork: t("xiadown.sniffDesk.sourceNetwork", language),
      sourceCandidate: t("xiadown.sniffDesk.sourceCandidate", language),
      sourceRejected: t("xiadown.sniffDesk.sourceRejected", language),
      sourceApiResponse: t("xiadown.sniffDesk.sourceApiResponse", language),
      sourceSubtitle: t("xiadown.sniffDesk.sourceSubtitle", language),
      kindVideo: t("xiadown.sniffDesk.kindVideo", language),
      kindAudio: t("xiadown.sniffDesk.kindAudio", language),
      kindLive: t("xiadown.sniffDesk.kindLive", language),
      kindManifest: t("xiadown.sniffDesk.kindManifest", language),
      kindImage: t("xiadown.sniffDesk.kindImage", language),
      kindSubtitle: t("xiadown.sniffDesk.kindSubtitle", language),
      kindApi: t("xiadown.sniffDesk.kindApi", language),
      kindDocument: t("xiadown.sniffDesk.kindDocument", language),
      kindFont: t("xiadown.sniffDesk.kindFont", language),
      kindArchive: t("xiadown.sniffDesk.kindArchive", language),
      kindOther: t("xiadown.sniffDesk.kindOther", language),
      reason: t("xiadown.sniffDesk.reason", language),
      reasonEmptyURL: t("xiadown.sniffDesk.reasonEmptyURL", language),
      reasonTooSmall: t("xiadown.sniffDesk.reasonTooSmall", language),
      reasonNotVideo: t("xiadown.sniffDesk.reasonNotVideo", language),
      reasonNoVideoSignal: t("xiadown.sniffDesk.reasonNoVideoSignal", language),
      reasonLowScore: t("xiadown.sniffDesk.reasonLowScore", language),
      reasonWeakCandidate: t("xiadown.sniffDesk.reasonWeakCandidate", language),
      reasonHttpStatus: t("xiadown.sniffDesk.reasonHttpStatus", language),
      reasonUnknown: t("xiadown.sniffDesk.reasonUnknown", language),
      reasonOther: t("xiadown.sniffDesk.reasonOther", language),
      mime: t("xiadown.sniffDesk.mime", language),
      score: t("xiadown.sniffDesk.score", language),
      size: t("xiadown.sniffDesk.size", language),
      copyLink: t("xiadown.sniffDesk.copyLink", language),
      linkCopied: t("xiadown.sniffDesk.linkCopied", language),
      copyFailed: t("xiadown.sniffDesk.copyFailed", language),
      downloadStarted: t("xiadown.sniffDesk.downloadStarted", language),
      downloadFailed: t("xiadown.sniffDesk.downloadFailed", language),
      preview: t("xiadown.sniffDesk.preview", language),
      previewFailed: t("xiadown.sniffDesk.previewFailed", language),
      previewUnsupported: t("xiadown.sniffDesk.previewUnsupported", language),
      details: t("xiadown.sniffDesk.details", language),
      resetFilters: t("xiadown.sniffDesk.resetFilters", language),
      clearResources: t("xiadown.sniffDesk.clearResources", language),
      clearResourcesTitle: t("xiadown.sniffDesk.clearResourcesTitle", language),
      clearResourcesMessage: t("xiadown.sniffDesk.clearResourcesMessage", language),
      clearResourcesSucceeded: t("xiadown.sniffDesk.clearResourcesSucceeded", language),
      clearResourcesFailed: t("xiadown.sniffDesk.clearResourcesFailed", language),
      errors: {
        operationCanceled: t("xiadown.sniffDesk.errors.operationCanceled", language),
        sessionRequired: t("xiadown.sniffDesk.errors.sessionRequired", language),
        sessionNotFound: t("xiadown.sniffDesk.errors.sessionNotFound", language),
        previewRequired: t("xiadown.sniffDesk.errors.previewRequired", language),
        previewUnavailable: t("xiadown.sniffDesk.errors.previewUnavailable", language),
        resourceRequired: t("xiadown.sniffDesk.errors.resourceRequired", language),
        resourceNotFound: t("xiadown.sniffDesk.errors.resourceNotFound", language),
        notPreviewable: t("xiadown.sniffDesk.errors.notPreviewable", language),
        resourceUrlRequired: t("xiadown.sniffDesk.errors.resourceUrlRequired", language),
        resourceUrlNotFetchable: t("xiadown.sniffDesk.errors.resourceUrlNotFetchable", language),
        notDownloadable: t("xiadown.sniffDesk.errors.notDownloadable", language),
        mediaSnapshotUnavailable: t("xiadown.sniffDesk.errors.mediaSnapshotUnavailable", language),
        resultUnavailable: t("xiadown.sniffDesk.errors.resultUnavailable", language),
        browserClosed: t("xiadown.sniffDesk.errors.browserClosed", language),
        browserClosing: t("xiadown.sniffDesk.errors.browserClosing", language),
        tabUnavailable: t("xiadown.sniffDesk.errors.tabUnavailable", language),
        browserUnavailable: t("xiadown.sniffDesk.errors.browserUnavailable", language),
        browserLaunchFailed: t("xiadown.sniffDesk.errors.browserLaunchFailed", language),
        resolveFailed: t("xiadown.sniffDesk.errors.resolveFailed", language),
      },
      cdpStatus: t("xiadown.sniffDesk.cdpStatus", language),
      cdpBrowser: t("xiadown.sniffDesk.cdpBrowser", language),
      cdpOrphan: t("xiadown.sniffDesk.cdpOrphan", language),
      cdpClose: t("xiadown.sniffDesk.cdpClose", language),
      cdpProcessCount: t("xiadown.sniffDesk.cdpProcessCount", language),
      cdpPid: t("xiadown.sniffDesk.cdpPid", language),
    },
    running: {
      title: t("xiadown.running.title", language),
      emptyAction: t("xiadown.running.emptyAction", language),
      emptyTitle: t("xiadown.running.emptyTitle", language),
      empty: t("xiadown.running.empty", language),
      playgroundHint: t("xiadown.running.playgroundHint", language),
      loading: t("xiadown.running.loading", language),
      overviewTitle: t("xiadown.running.overviewTitle", language),
      taskCount: t("xiadown.running.taskCount", language),
      overallProgress: t("xiadown.running.overallProgress", language),
      throughput: t("xiadown.running.throughput", language),
      elapsed: t("xiadown.running.elapsed", language),
      runningCount: t("xiadown.running.runningCount", language),
      queuedCount: t("xiadown.running.queuedCount", language),
      downloadSpeed: t("xiadown.running.downloadSpeed", language),
      transcodeSpeed: t("xiadown.running.transcodeSpeed", language),
      runningCountLine: t("xiadown.running.runningCountLine", language),
      queuedCountLine: t("xiadown.running.queuedCountLine", language),
      downloadSpeedLine: t("xiadown.running.downloadSpeedLine", language),
      transcodeSpeedLine: t("xiadown.running.transcodeSpeedLine", language),
      rangeLine: t("xiadown.running.rangeLine", language),
      percentLabel: t("xiadown.running.percentLabel", language),
      unavailable: t("xiadown.running.unavailable", language),
      separator: t("xiadown.running.separator", language),
      summarySeparator: t("xiadown.running.summarySeparator", language),
      units: {
        bytesPerSecond: t("xiadown.running.units.bytesPerSecond", language),
        framesPerSecond: t(
          "xiadown.running.units.framesPerSecond",
          language,
        ),
        speedFactor: t("xiadown.running.units.speedFactor", language),
      },
      progressFallback: t("xiadown.running.progressFallback", language),
      downloadBadge: t("xiadown.running.downloadBadge", language),
      transcodeBadge: t("xiadown.running.transcodeBadge", language),
      source: t("xiadown.running.source", language),
      createdAt: t("xiadown.running.createdAt", language),
      localSource: t("xiadown.running.localSource", language),
      stage: t("xiadown.running.stage", language),
      status: t("xiadown.running.status", language),
      eta: t("xiadown.running.eta", language),
      cancelConfirmTitle: t("xiadown.running.cancelConfirmTitle", language),
      cancelConfirmDescription: t(
        "xiadown.running.cancelConfirmDescription",
        language,
      ),
      stageLabels: {
        starting: t("xiadown.running.stageLabels.starting", language),
        preparing: t("xiadown.running.stageLabels.preparing", language),
        fetchingMetadata: t(
          "xiadown.running.stageLabels.fetchingMetadata",
          language,
        ),
        transcoding: t("xiadown.running.stageLabels.transcoding", language),
        downloading: t("xiadown.running.stageLabels.downloading", language),
        downloadingVideo: t(
          "xiadown.running.stageLabels.downloadingVideo",
          language,
        ),
        downloadingAudio: t(
          "xiadown.running.stageLabels.downloadingAudio",
          language,
        ),
        downloadingSubtitles: t(
          "xiadown.running.stageLabels.downloadingSubtitles",
          language,
        ),
        downloadingThumbnail: t(
          "xiadown.running.stageLabels.downloadingThumbnail",
          language,
        ),
        muxing: t("xiadown.running.stageLabels.muxing", language),
        cleaningUp: t("xiadown.running.stageLabels.cleaningUp", language),
        postProcessing: t(
          "xiadown.running.stageLabels.postProcessing",
          language,
        ),
        queued: t("xiadown.running.stageLabels.queued", language),
        running: t("xiadown.running.stageLabels.running", language),
        completed: t("xiadown.running.stageLabels.completed", language),
        failed: t("xiadown.running.stageLabels.failed", language),
        canceled: t("xiadown.running.stageLabels.canceled", language),
      },
    },
    completed: {
      title: t("xiadown.completed.title", language),
      emptyTasks: t("xiadown.completed.emptyTasks", language),
      emptyLibrary: t("xiadown.completed.emptyLibrary", language),
      emptyFiles: t("xiadown.completed.emptyFiles", language),
      detailEmpty: t("xiadown.completed.detailEmpty", language),
      records: t("xiadown.completed.records", language),
      outputs: t("xiadown.completed.outputs", language),
      info: t("xiadown.completed.info", language),
      taskDetail: t("xiadown.completed.taskDetail", language),
      taskDtoTitle: t("xiadown.completed.taskDtoTitle", language),
      taskDtoDescription: t("xiadown.completed.taskDtoDescription", language),
      openTaskDto: t("xiadown.completed.openTaskDto", language),
      copyDownloadUrl: t("xiadown.completed.copyDownloadUrl", language),
      downloadUrlCopied: t("xiadown.completed.downloadUrlCopied", language),
      copyFailed: t("xiadown.completed.copyFailed", language),
      renameTask: t("xiadown.completed.renameTask", language),
      renameTaskTitle: t("xiadown.completed.renameTaskTitle", language),
      renameTaskNameLabel: t(
        "xiadown.completed.renameTaskNameLabel",
        language,
      ),
      renameTaskNamePlaceholder: t(
        "xiadown.completed.renameTaskNamePlaceholder",
        language,
      ),
      renameFile: t("xiadown.completed.renameFile", language),
      renameFileTitle: t("xiadown.completed.renameFileTitle", language),
      renameFileNameLabel: t(
        "xiadown.completed.renameFileNameLabel",
        language,
      ),
      renameFileNamePlaceholder: t(
        "xiadown.completed.renameFileNamePlaceholder",
        language,
      ),
      renameNameRequired: t(
        "xiadown.completed.renameNameRequired",
        language,
      ),
      renameNameInvalid: t(
        "xiadown.completed.renameNameInvalid",
        language,
      ),
      renameNameTooLong: t(
        "xiadown.completed.renameNameTooLong",
        language,
      ),
      taskDataFields: {
        name: t("xiadown.completed.taskDataFields.name", language),
        url: t("xiadown.completed.taskDataFields.url", language),
        inputPath: t("xiadown.completed.taskDataFields.inputPath", language),
        format: t("xiadown.completed.taskDataFields.format", language),
        preset: t("xiadown.completed.taskDataFields.preset", language),
        videoCodec: t("xiadown.completed.taskDataFields.videoCodec", language),
        audioCodec: t("xiadown.completed.taskDataFields.audioCodec", language),
        qualityMode: t("xiadown.completed.taskDataFields.qualityMode", language),
        scale: t("xiadown.completed.taskDataFields.scale", language),
        deleteSourceFileAfterTranscode: t(
          "xiadown.completed.taskDataFields.deleteSourceFileAfterTranscode",
          language,
        ),
        enabled: t("xiadown.completed.taskDataFields.enabled", language),
        kind: t("xiadown.completed.taskDataFields.kind", language),
        status: t("xiadown.completed.taskDataFields.status", language),
        failureReason: t(
          "xiadown.completed.taskDataFields.failureReason",
          language,
        ),
        errorCode: t("xiadown.completed.taskDataFields.errorCode", language),
        domain: t("xiadown.completed.taskDataFields.domain", language),
        platform: t("xiadown.completed.taskDataFields.platform", language),
        uploader: t("xiadown.completed.taskDataFields.uploader", language),
        publishTime: t(
          "xiadown.completed.taskDataFields.publishTime",
          language,
        ),
        startedAt: t("xiadown.completed.taskDataFields.startedAt", language),
        finishedAt: t("xiadown.completed.taskDataFields.finishedAt", language),
        createdAt: t("xiadown.completed.taskDataFields.createdAt", language),
      },
      fileDetail: t("xiadown.completed.fileDetail", language),
      searchTasks: t("xiadown.completed.searchTasks", language),
      searchFiles: t("xiadown.completed.searchFiles", language),
      searchFilter: t("xiadown.completed.searchFilter", language),
      total: t("xiadown.completed.total", language),
      taskCountLabel: t("xiadown.completed.taskCountLabel", language),
      fileCountLabel: t("xiadown.completed.fileCountLabel", language),
      perPage: t("xiadown.completed.perPage", language),
      itemUnit: t("xiadown.completed.itemUnit", language),
      page: t("xiadown.completed.page", language),
      pageSuffix: t("xiadown.completed.pageSuffix", language),
      taskStatus: t("xiadown.completed.taskStatus", language),
      source: t("xiadown.completed.source", language),
      fileType: t("xiadown.completed.fileType", language),
      fileFormat: t("xiadown.completed.fileFormat", language),
      fileInfo: t("xiadown.completed.fileInfo", language),
      transcodedFrom: t("xiadown.completed.transcodedFrom", language),
      selectFiles: t("xiadown.completed.selectFiles", language),
      selectAll: t("xiadown.completed.selectAll", language),
      clearSelection: t("xiadown.completed.clearSelection", language),
      clearMissingFiles: t("xiadown.completed.clearMissingFiles", language),
      confirmClearMissingFiles: t(
        "xiadown.completed.confirmClearMissingFiles",
        language,
      ),
      clearMissingFilesRemovedToast: t(
        "xiadown.completed.clearMissingFilesRemovedToast",
        language,
      ),
      clearMissingFilesNoneToast: t(
        "xiadown.completed.clearMissingFilesNoneToast",
        language,
      ),
      fileMaintenanceFailed: t(
        "xiadown.completed.fileMaintenanceFailed",
        language,
      ),
      selectionSummary: t("xiadown.completed.selectionSummary", language),
      selectionUnit: t("xiadown.completed.selectionUnit", language),
      lineUnit: t("xiadown.completed.lineUnit", language),
      lineCount: t("xiadown.completed.lineCount", language),
      deleteFiles: t("xiadown.completed.deleteFiles", language),
      deleteTaskTitle: t("xiadown.completed.deleteTaskTitle", language),
      deleteTasksTitle: t("xiadown.completed.deleteTasksTitle", language),
      deleteFileTitle: t("xiadown.completed.deleteFileTitle", language),
      deleteFilesTitle: t("xiadown.completed.deleteFilesTitle", language),
      deleteTaskMessage: t("xiadown.completed.deleteTaskMessage", language),
      deleteTasksMessage: t("xiadown.completed.deleteTasksMessage", language),
      deleteFileMessage: t("xiadown.completed.deleteFileMessage", language),
      deleteFilesMessage: t("xiadown.completed.deleteFilesMessage", language),
      previousPage: t("xiadown.completed.previousPage", language),
      nextPage: t("xiadown.completed.nextPage", language),
      previewPlay: t("xiadown.completed.previewPlay", language),
      previewPause: t("xiadown.completed.previewPause", language),
      previewSeek: t("xiadown.completed.previewSeek", language),
      previewMute: t("xiadown.completed.previewMute", language),
      previewUnmute: t("xiadown.completed.previewUnmute", language),
      previewVolume: t("xiadown.completed.previewVolume", language),
      previewWindowFullscreen: t(
        "xiadown.completed.previewWindowFullscreen",
        language,
      ),
      previewWindowRestore: t(
        "xiadown.completed.previewWindowRestore",
        language,
      ),
      previewEnterFullscreen: t(
        "xiadown.completed.previewEnterFullscreen",
        language,
      ),
      previewExitFullscreen: t(
        "xiadown.completed.previewExitFullscreen",
        language,
      ),
      previewLoading: t("xiadown.completed.previewLoading", language),
      previewLoadingStream: t(
        "xiadown.completed.previewLoadingStream",
        language,
      ),
      previewPlaybackStalled: t(
        "xiadown.completed.previewPlaybackStalled",
        language,
      ),
      noPreview: t("xiadown.completed.noPreview", language),
      previewTooLarge: t("xiadown.completed.previewTooLarge", language),
      noSelectedTask: t("xiadown.completed.noSelectedTask", language),
      noSelectedFile: t("xiadown.completed.noSelectedFile", language),
      relinkDialogTitle: t("xiadown.completed.relinkDialogTitle", language),
      relinkNoMissing: t("xiadown.completed.relinkNoMissing", language),
      relinkChooseFolderTitle: t("xiadown.completed.relinkChooseFolderTitle", language),
      relinkScanFolder: t("xiadown.completed.relinkScanFolder", language),
      relinkApply: t("xiadown.completed.relinkApply", language),
      relinkApplySelected: t("xiadown.completed.relinkApplySelected", language),
      relinkStatusMissing: t("xiadown.completed.relinkStatusMissing", language),
      relinkStatusChecking: t("xiadown.completed.relinkStatusChecking", language),
      relinkStatusNewPath: t("xiadown.completed.relinkStatusNewPath", language),
      relinkScanFoundToast: t("xiadown.completed.relinkScanFoundToast", language),
      relinkScanNoneToast: t("xiadown.completed.relinkScanNoneToast", language),
      relinkScanFailed: t("xiadown.completed.relinkScanFailed", language),
      relinkApplySuccessToast: t("xiadown.completed.relinkApplySuccessToast", language),
      relinkApplyFailed: t("xiadown.completed.relinkApplyFailed", language),
      taskNoFiles: t("xiadown.completed.taskNoFiles", language),
      updatedAt: t("xiadown.completed.updatedAt", language),
      videoCount: t("xiadown.completed.videoCount", language),
      subtitleCount: t("xiadown.completed.subtitleCount", language),
      imageCount: t("xiadown.completed.imageCount", language),
      typeVideo: t("xiadown.completed.typeVideo", language),
      typeAudio: t("xiadown.completed.typeAudio", language),
      typeSubtitle: t("xiadown.completed.typeSubtitle", language),
      typeImage: t("xiadown.completed.typeImage", language),
      typeManifest: t("xiadown.completed.typeManifest", language),
      typeApi: t("xiadown.completed.typeApi", language),
      typeDocument: t("xiadown.completed.typeDocument", language),
      typeFont: t("xiadown.completed.typeFont", language),
      typeArchive: t("xiadown.completed.typeArchive", language),
      typeOther: t("xiadown.completed.typeOther", language),
      resolution: t("xiadown.completed.resolution", language),
      frameRate: t("xiadown.completed.frameRate", language),
      duration: t("xiadown.completed.duration", language),
      channels: t("xiadown.completed.channels", language),
      dpi: t("xiadown.completed.dpi", language),
      codec: t("xiadown.completed.codec", language),
      bitrate: t("xiadown.completed.bitrate", language),
      videoBitrate: t("xiadown.completed.videoBitrate", language),
      audioBitrate: t("xiadown.completed.audioBitrate", language),
      fileSize: t("xiadown.completed.fileSize", language),
      originalFormat: t("xiadown.completed.originalFormat", language),
      succeeded: t("xiadown.completed.succeeded", language),
      failed: t("xiadown.completed.failed", language),
      canceled: t("xiadown.completed.canceled", language),
    },
    welcome: {
      title: t("xiadown.welcome.title", language),
      subtitle: t("xiadown.welcome.subtitle", language),
      language: t("xiadown.welcome.language", language),
      proxy: t("xiadown.welcome.proxy", language),
      dependencies: t("xiadown.welcome.dependencies", language),
      dependencyStatus: t("xiadown.welcome.dependencyStatus", language),
      latestVersion: t("xiadown.welcome.latestVersion", language),
    },
    settings: {
      title: t("xiadown.settings.title", language),
      tabs: {
        general: t("xiadown.settings.tabs.general", language),
        appearance: t("xiadown.settings.tabs.appearance", language),
        equalizer: t("xiadown.settings.tabs.equalizer", language),
        player: t("xiadown.settings.tabs.player", language),
        download: t("xiadown.settings.tabs.download", language),
        about: t("xiadown.settings.tabs.about", language),
      },
      startup: t("xiadown.settings.startup", language),
      tray: t("xiadown.settings.tray", language),
      menuBar: t("xiadown.settings.menuBar", language),
      syncedLyrics: t("xiadown.settings.syncedLyrics", language),
      romanizedLyrics: t("xiadown.settings.romanizedLyrics", language),
      pinyinLyrics: t("xiadown.settings.pinyinLyrics", language),
      playbackAudioQuality: t("xiadown.settings.playbackAudioQuality", language),
      macOSOnly: t("xiadown.settings.macOSOnly", language),
      downloadDirectory: t("xiadown.settings.downloadDirectory", language),
      ytdlpConcurrentDownloads: t("xiadown.settings.ytdlpConcurrentDownloads", language),
      ytdlpConcurrentDownloadsHelp: t("xiadown.settings.ytdlpConcurrentDownloadsHelp", language),
      ytdlpConcurrentFragments: t("xiadown.settings.ytdlpConcurrentFragments", language),
      ytdlpConcurrentFragmentsHelp: t("xiadown.settings.ytdlpConcurrentFragmentsHelp", language),
      sniffBrowser: t("xiadown.settings.sniffBrowser", language),
      refreshBrowsers: t("xiadown.settings.refreshBrowsers", language),
      browserData: t("xiadown.settings.browserData", language),
      browserDataSize: t("xiadown.settings.browserDataSize", language),
      browserDataOpen: t("xiadown.settings.browserDataOpen", language),
      browserDataClear: t("xiadown.settings.browserDataClear", language),
      resourceSniffScope: t("xiadown.settings.resourceSniffScope", language),
      resourceSniffMinBytes: t("xiadown.settings.resourceSniffMinBytes", language),
      resourceSniffRetain: t("xiadown.settings.resourceSniffRetain", language),
      language: t("xiadown.settings.language", language),
      logLevel: t("xiadown.settings.logLevel", language),
      themePack: t("xiadown.settings.themePack", language),
      accent: t("xiadown.settings.accent", language),
      accentColor: t("xiadown.settings.accentColor", language),
      fontFamily: t("xiadown.settings.fontFamily", language),
      fontSize: t("xiadown.settings.fontSize", language),
      colorScheme: t("xiadown.settings.colorScheme", language),
      appearanceMode: t("xiadown.settings.appearanceMode", language),
      sidebarStyle: t("xiadown.settings.sidebarStyle", language),
      systemProxy: t("xiadown.settings.systemProxy", language),
      manualProxy: t("xiadown.settings.manualProxy", language),
      noProxy: t("xiadown.settings.noProxy", language),
      proxy: t("xiadown.settings.proxy", language),
      host: t("xiadown.settings.host", language),
      port: t("xiadown.settings.port", language),
      username: t("xiadown.settings.username", language),
      password: t("xiadown.settings.password", language),
      timeout: t("xiadown.settings.timeout", language),
      scheme: t("xiadown.settings.scheme", language),
      noProxyList: t("xiadown.settings.noProxyList", language),
      status: t("xiadown.settings.status", language),
      checking: t("xiadown.settings.checking", language),
      notConfigured: t("xiadown.settings.notConfigured", language),
      unavailable: t("xiadown.settings.unavailable", language),
      systemSource: t("xiadown.settings.systemSource", language),
      vpnSource: t("xiadown.settings.vpnSource", language),
      editProxy: t("xiadown.settings.editProxy", language),
      proxyDialogTitle: t("xiadown.settings.proxyDialogTitle", language),
      proxyDialogHint: t("xiadown.settings.proxyDialogHint", language),
      aboutText: t("xiadown.settings.aboutText", language),
      otherSoftware: t("xiadown.settings.otherSoftware", language),
      generalDescription: t("xiadown.settings.generalDescription", language),
      appearanceDescription: t(
        "xiadown.settings.appearanceDescription",
        language,
      ),
      proxyDescription: t("xiadown.settings.proxyDescription", language),
      menuBarOptions: {
        always: t("xiadown.settings.menuBarOptions.always", language),
        whenRunning: t("xiadown.settings.menuBarOptions.whenRunning", language),
        never: t("xiadown.settings.menuBarOptions.never", language),
      },
      resourceSniffScopeOptions: {
        default: t("xiadown.settings.resourceSniffScopeOptions.default", language),
        advanced: t("xiadown.settings.resourceSniffScopeOptions.advanced", language),
        all: t("xiadown.settings.resourceSniffScopeOptions.all", language),
      },
      resourceSniffMinBytesOptions: {
        kb8: t("xiadown.settings.resourceSniffMinBytesOptions.kb8", language),
        kb16: t("xiadown.settings.resourceSniffMinBytesOptions.kb16", language),
        kb64: t("xiadown.settings.resourceSniffMinBytesOptions.kb64", language),
        kb256: t("xiadown.settings.resourceSniffMinBytesOptions.kb256", language),
      },
      playbackAudioQualityOptions: {
        auto: t("xiadown.settings.playbackAudioQualityOptions.auto", language),
        low: t("xiadown.settings.playbackAudioQualityOptions.low", language),
        medium: t("xiadown.settings.playbackAudioQualityOptions.medium", language),
        high: t("xiadown.settings.playbackAudioQualityOptions.high", language),
      },
      colorSchemeOptions: {
        default: t("xiadown.settings.colorSchemeOptions.default", language),
        contrast: t("xiadown.settings.colorSchemeOptions.contrast", language),
        slate: t("xiadown.settings.colorSchemeOptions.slate", language),
        warm: t("xiadown.settings.colorSchemeOptions.warm", language),
      },
      sidebarStyleOptions: {
        glass: t("xiadown.settings.sidebarStyleOptions.glass", language),
        contrast: t("xiadown.settings.sidebarStyleOptions.contrast", language),
        pixel: t("xiadown.settings.sidebarStyleOptions.pixel", language),
      },
      accentOptions: {
        theme: t("xiadown.settings.accentOptions.theme", language),
        color: t("xiadown.settings.accentOptions.color", language),
      },
      systemProxyEmpty: t("xiadown.settings.systemProxyEmpty", language),
      proxyTestSucceeded: t("xiadown.settings.proxyTestSucceeded", language),
      proxyTestFailed: t("xiadown.settings.proxyTestFailed", language),
      equalizer: {
        title: t("xiadown.settings.equalizer.title", language),
        enable: t("xiadown.settings.equalizer.enable", language),
        preset: t("xiadown.settings.equalizer.preset", language),
        visualizer: t("xiadown.settings.equalizer.visualizer", language),
        visualizerArtworkEffect: t("xiadown.settings.equalizer.visualizerArtworkEffect", language),
        visualizerSpectrumEffect: t("xiadown.settings.equalizer.visualizerSpectrumEffect", language),
        bands: t("xiadown.settings.equalizer.bands", language),
        preamp: t("xiadown.settings.equalizer.preamp", language),
        reset: t("xiadown.settings.equalizer.reset", language),
        retry: t("xiadown.settings.equalizer.retry", language),
        openSettings: t("xiadown.settings.equalizer.openSettings", language),
        custom: t("xiadown.settings.equalizer.custom", language),
        macOSOnly: t("xiadown.settings.equalizer.macOSOnly", language),
        permissionName: t("xiadown.settings.equalizer.permissionName", language),
        permissionGuideHint: t("xiadown.settings.equalizer.permissionGuideHint", language),
        status: {
          off: t("xiadown.settings.equalizer.status.off", language),
          active: t("xiadown.settings.equalizer.status.active", language),
          standby: t("xiadown.settings.equalizer.status.standby", language),
          permissionNeeded: t("xiadown.settings.equalizer.status.permissionNeeded", language),
          unsupported: t("xiadown.settings.equalizer.status.unsupported", language),
          error: t("xiadown.settings.equalizer.status.error", language),
        },
        messages: {
          active: t("xiadown.settings.equalizer.messages.active", language),
          standby: t("xiadown.settings.equalizer.messages.standby", language),
          permissionNeeded: t("xiadown.settings.equalizer.messages.permissionNeeded", language),
          unsupported: t("xiadown.settings.equalizer.messages.unsupported", language),
          error: t("xiadown.settings.equalizer.messages.error", language),
        },
        presets: {
          flat: t("xiadown.settings.equalizer.presets.flat", language),
          acoustic: t("xiadown.settings.equalizer.presets.acoustic", language),
          bassBooster: t("xiadown.settings.equalizer.presets.bassBooster", language),
          bassReducer: t("xiadown.settings.equalizer.presets.bassReducer", language),
          classical: t("xiadown.settings.equalizer.presets.classical", language),
          dance: t("xiadown.settings.equalizer.presets.dance", language),
          deep: t("xiadown.settings.equalizer.presets.deep", language),
          electronic: t("xiadown.settings.equalizer.presets.electronic", language),
          hipHop: t("xiadown.settings.equalizer.presets.hipHop", language),
          jazz: t("xiadown.settings.equalizer.presets.jazz", language),
          latin: t("xiadown.settings.equalizer.presets.latin", language),
          loudness: t("xiadown.settings.equalizer.presets.loudness", language),
          lounge: t("xiadown.settings.equalizer.presets.lounge", language),
          piano: t("xiadown.settings.equalizer.presets.piano", language),
          pop: t("xiadown.settings.equalizer.presets.pop", language),
          rnb: t("xiadown.settings.equalizer.presets.rnb", language),
          rock: t("xiadown.settings.equalizer.presets.rock", language),
          smallSpeakers: t("xiadown.settings.equalizer.presets.smallSpeakers", language),
          spokenWord: t("xiadown.settings.equalizer.presets.spokenWord", language),
          trebleBooster: t("xiadown.settings.equalizer.presets.trebleBooster", language),
          trebleReducer: t("xiadown.settings.equalizer.presets.trebleReducer", language),
          vocalBooster: t("xiadown.settings.equalizer.presets.vocalBooster", language),
        },
        visualizers: {
          off: t("xiadown.settings.equalizer.visualizers.off", language),
          halo: t("xiadown.settings.equalizer.visualizers.halo", language),
          ring: t("xiadown.settings.equalizer.visualizers.ring", language),
          neonPulse: t("xiadown.settings.equalizer.visualizers.neonPulse", language),
          pondRipple: t("xiadown.settings.equalizer.visualizers.pondRipple", language),
          bars: t("xiadown.settings.equalizer.visualizers.bars", language),
          mirror: t("xiadown.settings.equalizer.visualizers.mirror", language),
          waveform: t("xiadown.settings.equalizer.visualizers.waveform", language),
          heatmap: t("xiadown.settings.equalizer.visualizers.heatmap", language),
        },
        visualizerGroups: {
          artwork: t("xiadown.settings.equalizer.visualizerGroups.artwork", language),
          spectrum: t("xiadown.settings.equalizer.visualizerGroups.spectrum", language),
          off: t("xiadown.settings.equalizer.visualizerGroups.off", language),
        },
      },
    },
    dependencies: {
      title: t("xiadown.dependencies.title", language),
      subtitle: t("xiadown.dependencies.subtitle", language),
      installed: t("xiadown.dependencies.installed", language),
      missing: t("xiadown.dependencies.missing", language),
      invalid: t("xiadown.dependencies.invalid", language),
      idle: t("xiadown.dependencies.idle", language),
      latestVersion: t("xiadown.dependencies.latestVersion", language),
      currentVersion: t("xiadown.dependencies.currentVersion", language),
      execPath: t("xiadown.dependencies.execPath", language),
      noRemoteVersionInfo: t(
        "xiadown.dependencies.noRemoteVersionInfo",
        language,
      ),
      reinstall: t("xiadown.dependencies.reinstall", language),
      downloading: t("xiadown.dependencies.downloading", language),
      extracting: t("xiadown.dependencies.extracting", language),
      verifying: t("xiadown.dependencies.verifying", language),
      installing: t("xiadown.dependencies.installing", language),
      missingDependency: t("xiadown.dependencies.missingDependency", language),
    },
    dialogs: {
      downloadTitle: t("xiadown.dialogs.downloadTitle", language),
      transcodeTitle: t("xiadown.dialogs.transcodeTitle", language),
      dependenciesRequiredTitle: t(
        "xiadown.dialogs.dependenciesRequiredTitle",
        language,
      ),
      dependenciesRequiredDescription: t(
        "xiadown.dialogs.dependenciesRequiredDescription",
        language,
      ),
      url: "URL",
      downloadPlaceholder: t("xiadown.dialogs.downloadPlaceholder", language),
      batchDownload: t("xiadown.dialogs.batchDownload", language),
      batchDownloadCount: t("xiadown.dialogs.batchDownloadCount", language),
      downloadUrlRequired: t("xiadown.dialogs.downloadUrlRequired", language),
      downloadUrlInvalid: t("xiadown.dialogs.downloadUrlInvalid", language),
      downloadUrlUnsupported: t("xiadown.dialogs.downloadUrlUnsupported", language),
      downloadUrlMultiple: t("xiadown.dialogs.downloadUrlMultiple", language),
      downloadBatchEmpty: t("xiadown.dialogs.downloadBatchEmpty", language),
      downloadBatchTooLarge: t("xiadown.dialogs.downloadBatchTooLarge", language),
      requestDownload: t("xiadown.dialogs.requestDownload", language),
      startSniffMode: t("xiadown.dialogs.startSniffMode", language),
      directDownload: t("xiadown.dialogs.directDownload", language),
      quickMode: t("xiadown.dialogs.quickMode", language),
      customMode: t("xiadown.dialogs.customMode", language),
      sniffMode: t("xiadown.dialogs.sniffMode", language),
      preset: t("xiadown.dialogs.preset", language),
      format: t("xiadown.dialogs.format", language),
      formatGroupVideo: t("xiadown.dialogs.formatGroupVideo", language),
      formatGroupAudio: t("xiadown.dialogs.formatGroupAudio", language),
      quality: t("xiadown.dialogs.quality", language),
      qualityBest: t("xiadown.dialogs.qualityBest", language),
      qualityBitrate: t("xiadown.dialogs.qualityBitrate", language),
      qualityAudio: t("xiadown.dialogs.qualityAudio", language),
      audioTrack: t("xiadown.dialogs.audioTrack", language),
      selectFormat: t("xiadown.dialogs.selectFormat", language),
      size: t("xiadown.dialogs.size", language),
      container: t("xiadown.dialogs.container", language),
      codec: t("xiadown.dialogs.codec", language),
      scaleOriginal: t("xiadown.dialogs.scaleOriginal", language),
      scaleCustom: t("xiadown.dialogs.scaleCustom", language),
      subtitles: t("xiadown.dialogs.subtitles", language),
      noSubtitle: t("xiadown.dialogs.noSubtitle", language),
      noTranscode: t("xiadown.dialogs.noTranscode", language),
      keepOnlyTranscodedFile: t(
        "xiadown.dialogs.keepOnlyTranscodedFile",
        language,
      ),
      parse: t("xiadown.dialogs.parse", language),
      parseAgain: t("xiadown.dialogs.parseAgain", language),
      enterSniffDesk: t("xiadown.dialogs.enterSniffDesk", language),
      parseFailedWithoutAppSession: t(
        "xiadown.dialogs.parseFailedWithoutAppSession",
        language,
      ),
      parseFailedWithAppSession: t(
        "xiadown.dialogs.parseFailedWithAppSession",
        language,
      ),
      resourceVerificationRequired: t(
        "xiadown.dialogs.resourceVerificationRequired",
        language,
      ),
      resourceNoMediaDetected: t(
        "xiadown.dialogs.resourceNoMediaDetected",
        language,
      ),
      resourceDouyinLVDetail: t(
        "xiadown.dialogs.resourceDouyinLVDetail",
        language,
      ),
      resourceDouyinRecommendLoginRequired: t(
        "xiadown.dialogs.resourceDouyinRecommendLoginRequired",
        language,
      ),
      profileConnectionRequired: t(
        "xiadown.dialogs.profileConnectionRequired",
        language,
      ),
      openConnections: t("xiadown.dialogs.openConnections", language),
      startSniff: t("xiadown.dialogs.startSniff", language),
      restartSniff: t("xiadown.dialogs.restartSniff", language),
      restartSniffShort: t("xiadown.dialogs.restartSniffShort", language),
      sniffReady: t("xiadown.dialogs.sniffReady", language),
      sniffBrowserOpen: t("xiadown.dialogs.sniffBrowserOpen", language),
      sniffNoActiveTab: t("xiadown.dialogs.sniffNoActiveTab", language),
      sniffBrowserExited: t("xiadown.dialogs.sniffBrowserExited", language),
      sniffUnsupportedDomainHint: t(
        "xiadown.dialogs.sniffUnsupportedDomain.hint",
        language,
      ),
      currentStatus: t("xiadown.dialogs.currentStatus", language),
      currentPage: t("xiadown.dialogs.currentPage", language),
      currentUser: t("xiadown.dialogs.currentUser", language),
      loggedIn: t("xiadown.dialogs.loggedIn", language),
      notLoggedIn: t("xiadown.dialogs.notLoggedIn", language),
      mediaTitle: t("xiadown.dialogs.mediaTitle", language),
      mediaAuthor: t("xiadown.dialogs.mediaAuthor", language),
      sniffParseFailed: t("xiadown.dialogs.sniffParseFailed", language),
      useAppSession: t("xiadown.dialogs.useAppSession", language),
      appSessionAvailable: t("xiadown.dialogs.appSessionAvailable", language),
      appSessionUnavailable: t("xiadown.dialogs.appSessionUnavailable", language),
      noAvailableAppSession: t("xiadown.dialogs.noAvailableAppSession", language),
      appSessionNotConfigured: t(
        "xiadown.dialogs.appSessionNotConfigured",
        language,
      ),
      appSessionCanEnable: t("xiadown.dialogs.appSessionCanEnable", language),
      appSessionCookiesDownload: t(
        "xiadown.dialogs.appSessionCookiesDownload",
        language,
      ),
      modifyLink: t("xiadown.dialogs.modifyLink", language),
      modifyFile: t("xiadown.dialogs.modifyFile", language),
      path: t("xiadown.dialogs.path", language),
      fileAddress: t("xiadown.dialogs.fileAddress", language),
      inspectingFile: t("xiadown.dialogs.inspectingFile", language),
      fileInspectFailed: t("xiadown.dialogs.fileInspectFailed", language),
      noCompatibleTranscodePreset: t(
        "xiadown.dialogs.noCompatibleTranscodePreset",
        language,
      ),
      nameHint: t("xiadown.dialogs.nameHint", language),
    },
    listen: {
      title: "Listen",
      subtitle: t("xiadown.listen.subtitle", language),
      hush: t("xiadown.listen.hush", language),
      muse: t("xiadown.listen.muse", language),
      linger: t("xiadown.listen.linger", language),
      hushTooltip: t("xiadown.listen.hushTooltip", language),
      museTooltip: t("xiadown.listen.museTooltip", language),
      lingerTooltip: t("xiadown.listen.lingerTooltip", language),
      audioQuality: t("xiadown.listen.audioQuality", language),
      audioQualityUnknown: t("xiadown.listen.audioQualityUnknown", language),
      audioQualityOptions: {
        low: t("xiadown.listen.audioQualityOptions.low", language),
        medium: t("xiadown.listen.audioQualityOptions.medium", language),
        high: t("xiadown.listen.audioQualityOptions.high", language),
      },
      localEmpty: t("xiadown.listen.localEmpty", language),
      localEmptyPrompt: t("xiadown.listen.localEmptyPrompt", language),
      localEmptyAction: t("xiadown.listen.localEmptyAction", language),
      localLoading: t("xiadown.listen.localLoading", language),
      localRefresh: t("xiadown.listen.localRefresh", language),
      localClearMissing: t("xiadown.listen.localClearMissing", language),
      localConfirmClearMissing: t("xiadown.listen.localConfirmClearMissing", language),
      localClearMissingRemovedToast: t("xiadown.listen.localClearMissingRemovedToast", language),
      localClearMissingNoneToast: t("xiadown.listen.localClearMissingNoneToast", language),
      localClearMissingFailed: t("xiadown.listen.localClearMissingFailed", language),
      localModifiedToday: t("xiadown.listen.localModifiedToday", language),
      localModifiedYesterday: t("xiadown.listen.localModifiedYesterday", language),
      localModifiedLast7Days: t("xiadown.listen.localModifiedLast7Days", language),
      localModifiedLast30Days: t("xiadown.listen.localModifiedLast30Days", language),
      localModifiedThisYear: t("xiadown.listen.localModifiedThisYear", language),
      localModifiedOlder: t("xiadown.listen.localModifiedOlder", language),
      randomStation: t("xiadown.listen.randomStation", language),
      searchLive: t("xiadown.listen.searchLive", language),
      searchOnline: t("xiadown.listen.searchOnline", language),
      searchLocal: t("xiadown.listen.searchLocal", language),
      searchSongs: t("xiadown.listen.searchSongs", language),
      searchArtists: t("xiadown.listen.searchArtists", language),
      searchPlaylists: t("xiadown.listen.searchPlaylists", language),
      sourceHome: t("xiadown.listen.sourceHome", language),
      sourceExplore: t("xiadown.listen.sourceExplore", language),
      sourceCharts: t("xiadown.listen.sourceCharts", language),
      sourceMoods: t("xiadown.listen.sourceMoods", language),
      sourceNew: t("xiadown.listen.sourceNew", language),
      sourceHistory: t("xiadown.listen.sourceHistory", language),
      groupLive: t("xiadown.listen.groupLive", language),
      liveStations: t("xiadown.listen.liveStations", language),
      liveLoading: t("xiadown.listen.liveLoading", language),
      liveUnavailable: t("xiadown.listen.liveUnavailable", language),
      liveEmpty: t("xiadown.listen.liveEmpty", language),
      addChannel: t("xiadown.listen.addChannel", language),
      editChannel: t("xiadown.listen.editChannel", language),
      removeChannel: t("xiadown.listen.removeChannel", language),
      confirmRemoveChannel: t("xiadown.listen.confirmRemoveChannel", language),
      manageColumns: t("xiadown.listen.manageColumns", language),
      customCatalogSummary: t("xiadown.listen.customCatalogSummary", language),
      addChannelPlaceholder: t("xiadown.listen.addChannelPlaceholder", language),
      channelURL: t("xiadown.listen.channelURL", language),
      channelTitle: t("xiadown.listen.channelTitle", language),
      channelName: t("xiadown.listen.channelName", language),
      channelColumn: t("xiadown.listen.channelColumn", language),
      noColumn: t("xiadown.listen.noColumn", language),
      channelDescription: t("xiadown.listen.channelDescription", language),
      channelThumbnail: t("xiadown.listen.channelThumbnail", language),
      channelVideoIdRequired: t("xiadown.listen.channelVideoIdRequired", language),
      channelNotLive: t("xiadown.listen.channelNotLive", language),
      channelTitleRequired: t("xiadown.listen.channelTitleRequired", language),
      addColumn: t("xiadown.listen.addColumn", language),
      editColumn: t("xiadown.listen.editColumn", language),
      saveColumn: t("xiadown.listen.saveColumn", language),
      removeColumn: t("xiadown.listen.removeColumn", language),
      confirmRemoveColumn: t("xiadown.listen.confirmRemoveColumn", language),
      customColumnPlaceholder: t("xiadown.listen.customColumnPlaceholder", language),
      builtInColumns: t("xiadown.listen.builtInColumns", language),
      customColumns: t("xiadown.listen.customColumns", language),
      readonlyColumn: t("xiadown.listen.readonlyColumn", language),
      noColumns: t("xiadown.listen.noColumns", language),
      columnTitleRequired: t("xiadown.listen.columnTitleRequired", language),
      columnAlreadyExists: t("xiadown.listen.columnAlreadyExists", language),
      userCatalogSaveFailed: t("xiadown.listen.userCatalogSaveFailed", language),
      retry: t("xiadown.listen.retry", language),
      groupLibrary: t("xiadown.listen.groupLibrary", language),
      libraryArtists: t("xiadown.listen.libraryArtists", language),
      likedMusic: t("xiadown.listen.likedMusic", language),
      groupCategories: t("xiadown.listen.groupCategories", language),
      groupArtists: t("xiadown.listen.groupArtists", language),
      groupPlaylist: t("xiadown.listen.groupPlaylist", language),
      playlistTypeAlbum: t("xiadown.listen.playlistTypeAlbum", language),
      playlistTypeSingle: t("xiadown.listen.playlistTypeSingle", language),
      playlistTypeEP: t("xiadown.listen.playlistTypeEP", language),
      playlistTypePlaylist: t("xiadown.listen.playlistTypePlaylist", language),
      playlistTrackCount: t("xiadown.listen.playlistTrackCount", language),
      playlistTrackCountMore: t("xiadown.listen.playlistTrackCountMore", language),
      groupRecommendations: t("xiadown.listen.groupRecommendations", language),
      groupRadio: t("xiadown.listen.groupRadio", language),
      shelfQuickPicks: t("xiadown.listen.shelfQuickPicks", language),
      shelfListenAgain: t("xiadown.listen.shelfListenAgain", language),
      shelfMixedForYou: t("xiadown.listen.shelfMixedForYou", language),
      shelfFeaturedPlaylists: t("xiadown.listen.shelfFeaturedPlaylists", language),
      shelfVideoCharts: t("xiadown.listen.shelfVideoCharts", language),
      shelfTopSongs: t("xiadown.listen.shelfTopSongs", language),
      shelfTopMusicVideos: t("xiadown.listen.shelfTopMusicVideos", language),
      shelfTopArtists: t("xiadown.listen.shelfTopArtists", language),
      shelfTrending: t("xiadown.listen.shelfTrending", language),
      shelfNewAlbums: t("xiadown.listen.shelfNewAlbums", language),
      shelfNewSingles: t("xiadown.listen.shelfNewSingles", language),
      shelfNewVideos: t("xiadown.listen.shelfNewVideos", language),
      shelfNewReleases: t("xiadown.listen.shelfNewReleases", language),
      shelfMoodsAndGenres: t("xiadown.listen.shelfMoodsAndGenres", language),
      liveBadge: t("xiadown.listen.liveBadge", language),
      liveStatusChecking: t("xiadown.listen.liveStatusChecking", language),
      liveStatusLive: t("xiadown.listen.liveStatusLive", language),
      liveStatusOffline: t("xiadown.listen.liveStatusOffline", language),
      liveStatusUpcoming: t("xiadown.listen.liveStatusUpcoming", language),
      liveStatusUnavailable: t("xiadown.listen.liveStatusUnavailable", language),
      liveStatusUnknown: t("xiadown.listen.liveStatusUnknown", language),
      adBadge: t("xiadown.listen.adBadge", language),
      browse: t("xiadown.listen.browse", language),
      upNext: t("xiadown.listen.upNext", language),
      play: t("xiadown.listen.play", language),
      pause: t("xiadown.listen.pause", language),
      stop: t("xiadown.listen.stop", language),
      loading: t("xiadown.listen.loading", language),
      idleStatus: t("xiadown.listen.idleStatus", language),
      nowPlaying: t("xiadown.listen.nowPlaying", language),
      playingStatus: t("xiadown.listen.playingStatus", language),
      pausedStatus: t("xiadown.listen.pausedStatus", language),
      loadingStatus: t("xiadown.listen.loadingStatus", language),
      errorStatus: t("xiadown.listen.errorStatus", language),
      errorCodeLabel: t("xiadown.listen.errorCodeLabel", language),
      idleSubtitle: t("xiadown.listen.idleSubtitle", language),
      previous: t("xiadown.listen.previous", language),
      next: t("xiadown.listen.next", language),
      playbackMode: t("xiadown.listen.playbackMode", language),
      playModeOrder: t("xiadown.listen.playModeOrder", language),
      playModeShuffle: t("xiadown.listen.playModeShuffle", language),
      playModeRepeat: t("xiadown.listen.playModeRepeat", language),
      mute: t("xiadown.listen.mute", language),
      unmute: t("xiadown.listen.unmute", language),
      volume: t("xiadown.listen.volume", language),
      seek: t("xiadown.listen.seek", language),
      favorite: t("xiadown.listen.favorite", language),
      favoriteUnavailable: t("xiadown.listen.favoriteUnavailable", language),
      selectStation: t("xiadown.listen.selectStation", language),
      collapseList: t("xiadown.listen.collapseList", language),
      openList: t("xiadown.listen.openList", language),
      onlineHint: t("xiadown.listen.onlineHint", language),
      onlineLoading: t("xiadown.listen.onlineLoading", language),
      onlineUnavailable: t("xiadown.listen.onlineUnavailable", language),
      onlineConnectionPrompt: t(
        "xiadown.listen.onlineConnectionPrompt",
        language,
      ),
      onlineAuthRequired: t("xiadown.listen.onlineAuthRequired", language),
      onlineAuthExpired: t("xiadown.listen.onlineAuthExpired", language),
      museGateTitle: t("xiadown.listen.museGateTitle", language),
      museGateSubtitle: t("xiadown.listen.museGateSubtitle", language),
      museGateSignIn: t("xiadown.listen.museGateSignIn", language),
      museGateLibrary: t("xiadown.listen.museGateLibrary", language),
      museGateLibraryDetail: t(
        "xiadown.listen.museGateLibraryDetail",
        language,
      ),
      museGateLiked: t("xiadown.listen.museGateLiked", language),
      museGateLikedDetail: t("xiadown.listen.museGateLikedDetail", language),
      museGateRecommendations: t(
        "xiadown.listen.museGateRecommendations",
        language,
      ),
      museGateRecommendationsDetail: t(
        "xiadown.listen.museGateRecommendationsDetail",
        language,
      ),
      museGateSession: t("xiadown.listen.museGateSession", language),
      museGateSessionDetail: t("xiadown.listen.museGateSessionDetail", language),
      museAccountFallbackName: t(
        "xiadown.listen.museAccountFallbackName",
        language,
      ),
      museAccountDisconnectedName: t(
        "xiadown.listen.museAccountDisconnectedName",
        language,
      ),
      museAccountTooltip: t("xiadown.listen.museAccountTooltip", language),
      museAccountSignOut: t("xiadown.listen.museAccountSignOut", language),
      onlineNetworkUnavailable: t(
        "xiadown.listen.onlineNetworkUnavailable",
        language,
      ),
      onlineServiceUnavailable: t(
        "xiadown.listen.onlineServiceUnavailable",
        language,
      ),
      openConnections: t("xiadown.listen.openConnections", language),
      refresh: t("xiadown.listen.refresh", language),
      contentEmpty: t("xiadown.listen.contentEmpty", language),
      onlineEmpty: t("xiadown.listen.onlineEmpty", language),
      searchLoading: t("xiadown.listen.searchLoading", language),
      searchUnavailable: t("xiadown.listen.searchUnavailable", language),
      searchEmpty: t("xiadown.listen.searchEmpty", language),
      loadMore: t("xiadown.listen.loadMore", language),
      seeAll: t("xiadown.listen.seeAll", language),
      playAll: t("xiadown.listen.playAll", language),
      playNext: t("xiadown.listen.playNext", language),
      addToQueue: t("xiadown.listen.addToQueue", language),
      addToLibrary: t("xiadown.listen.addToLibrary", language),
      shuffleAll: t("xiadown.listen.shuffleAll", language),
      clearQueue: t("xiadown.listen.clearQueue", language),
      undoQueue: t("xiadown.listen.undoQueue", language),
      redoQueue: t("xiadown.listen.redoQueue", language),
      editQueue: t("xiadown.listen.editQueue", language),
      doneQueue: t("xiadown.listen.doneQueue", language),
      removeFromQueue: t("xiadown.listen.removeFromQueue", language),
      moveQueueItemUp: t("xiadown.listen.moveQueueItemUp", language),
      moveQueueItemDown: t("xiadown.listen.moveQueueItemDown", language),
      airPlay: t("xiadown.listen.airPlay", language),
      video: t("xiadown.listen.video", language),
      fitWindow: t("xiadown.listen.fitWindow", language),
      fitVideo: t("xiadown.listen.fitVideo", language),
      lockVideo: t("xiadown.listen.lockVideo", language),
      unlockVideo: t("xiadown.listen.unlockVideo", language),
      noVideo: t("xiadown.listen.noVideo", language),
      lyrics: t("xiadown.listen.lyrics", language),
      lyricsEmpty: t("xiadown.listen.lyricsEmpty", language),
      more: t("xiadown.listen.more", language),
      openPage: t("xiadown.listen.openPage", language),
      copyLink: t("xiadown.listen.copyLink", language),
      linkCopied: t("xiadown.listen.linkCopied", language),
      artistShuffle: t("xiadown.listen.artistShuffle", language),
      artistMix: t("xiadown.listen.artistMix", language),
      artistSubscribe: t("xiadown.listen.artistSubscribe", language),
      artistUnsubscribe: t("xiadown.listen.artistUnsubscribe", language),
      artistLoading: t("xiadown.listen.artistLoading", language),
      artistUnavailable: t("xiadown.listen.artistUnavailable", language),
      artistEmpty: t("xiadown.listen.artistEmpty", language),
      playlistLoading: t("xiadown.listen.playlistLoading", language),
      playlistEmpty: t("xiadown.listen.playlistEmpty", language),
      upNextEmpty: t("xiadown.listen.upNextEmpty", language),
      savePlaylist: t("xiadown.listen.savePlaylist", language),
      removePlaylist: t("xiadown.listen.removePlaylist", language),
      playerUnavailable: t("xiadown.listen.playerUnavailable", language),
    },
    whatsNew: {
      title: t("xiadown.whatsNew.title", language),
      empty: t("xiadown.whatsNew.empty", language),
    },
    about: {
      updateStatus: t("xiadown.about.updateStatus", language),
      currentVersion: t("xiadown.about.currentVersion", language),
      latestVersion: t("xiadown.about.latestVersion", language),
      status: t("xiadown.about.status", language),
      latestOk: t("xiadown.about.latestOk", language),
      latestAvailable: t("xiadown.about.latestAvailable", language),
      latestFailed: t("xiadown.about.latestFailed", language),
      viewChangelog: t("xiadown.about.viewChangelog", language),
      viewReleaseNotes: t("xiadown.about.viewReleaseNotes", language),
      noReleaseNotes: t("xiadown.about.noReleaseNotes", language),
      releaseNotesClose: t("xiadown.about.releaseNotesClose", language),
      checkUpdates: t("xiadown.about.checkUpdates", language),
      recheck: t("xiadown.about.recheck", language),
      downloadAndInstall: t("xiadown.about.downloadAndInstall", language),
      restartAfterUpdate: t("xiadown.about.restartAfterUpdate", language),
      downloading: t("xiadown.about.downloading", language),
      installing: t("xiadown.about.installing", language),
      craftedBy: t("xiadown.about.craftedBy", language),
      contact: t("xiadown.about.contact", language),
      feedback: t("xiadown.about.feedback", language),
      sendFeedback: t("xiadown.about.sendFeedback", language),
      email: t("xiadown.about.email", language),
      twitter: t("xiadown.about.twitter", language),
      website: t("xiadown.about.website", language),
      github: t("xiadown.about.github", language),
      dreamCreator: t("xiadown.about.dreamCreator", language),
      dreamCreatorDescription: t(
        "xiadown.about.dreamCreatorDescription",
        language,
      ),
      hush: t("xiadown.about.hush", language),
      hushDescription: t("xiadown.about.hushDescription", language),
    },
    common: {
      systemDefault: t("xiadown.common.systemDefault", language),
      current: t("xiadown.common.current", language),
      customColor: t("xiadown.common.customColor", language),
      light: t("xiadown.common.light", language),
      dark: t("xiadown.common.dark", language),
      auto: t("xiadown.common.auto", language),
      followSystem: t("xiadown.common.followSystem", language),
      ready: t("xiadown.common.ready", language),
      unknown: t("xiadown.common.unknown", language),
      browse: t("xiadown.common.browse", language),
      colorOptions: {
        blue: t("xiadown.common.colorOptions.blue", language),
        indigo: t("xiadown.common.colorOptions.indigo", language),
        violet: t("xiadown.common.colorOptions.violet", language),
        rose: t("xiadown.common.colorOptions.rose", language),
        red: t("xiadown.common.colorOptions.red", language),
        orange: t("xiadown.common.colorOptions.orange", language),
        amber: t("xiadown.common.colorOptions.amber", language),
        teal: t("xiadown.common.colorOptions.teal", language),
      },
      languages: {
        en: t("settings.language.option.en", language),
        zhCN: t("settings.language.option.zhCN", language),
        zhTW: t("settings.language.option.zhTW", language),
        jaJP: t("settings.language.option.jaJP", language),
        koKR: t("settings.language.option.koKR", language),
        es419: t("settings.language.option.es419", language),
        ptBR: t("settings.language.option.ptBR", language),
        idID: t("settings.language.option.idID", language),
        viVN: t("settings.language.option.viVN", language),
      },
    },
  };
}

type XiaText = ReturnType<typeof buildText>;

export function getXiaText(language?: string): XiaText {
  return buildText(normalizeLanguage(language ?? ""));
}

export function isZhLanguage(language?: string) {
  return (language ?? "").toLowerCase().startsWith("zh");
}

export function resolveLibraryCoverFile(
  library?: LibraryDTO | null,
): LibraryFileDTO | null {
  const items = (library?.files ?? [])
    .filter(
      (file) =>
        (file.kind ?? "").trim().toLowerCase() === "thumbnail" &&
        !file.state.deleted,
    )
    .filter((file) => Boolean(file.storage.localPath?.trim()));
  return items[0] ?? null;
}

export function resolveLibraryCoverURL(
  baseURL: string,
  library?: LibraryDTO | null,
) {
  const path =
    resolveLibraryCoverFile(library)?.storage.localPath?.trim() ?? "";
  return buildAssetPreviewURL(baseURL, path);
}

export function isAudioLibraryFile(file?: LibraryFileDTO | null) {
  if (!file) {
    return false;
  }
  const kind = (file.kind ?? "").trim().toLowerCase();
  if (kind === "audio") {
    return true;
  }
  if (kind === "transcode") {
    return Boolean(file.media?.audioCodec || file.media?.channels);
  }
  const path = (file.storage.localPath ?? "").toLowerCase();
  return [
    ".aac",
    ".aif",
    ".aiff",
    ".alac",
    ".caf",
    ".flac",
    ".m4a",
    ".m4b",
    ".mp3",
    ".mp4",
    ".mpga",
    ".oga",
    ".ogg",
    ".opus",
    ".wav",
    ".wave",
    ".weba",
    ".webm",
  ].some((suffix) => path.endsWith(suffix));
}
