import type { LibraryDTO, LibraryFileDTO } from "@/shared/contracts/library";
import { t, type SupportedLanguage } from "@/shared/i18n";
import { buildAssetPreviewURL } from "@/shared/utils/resourceHelpers";

export {
  XIA_DEFAULT_THEME_PACK_ID,
  XIA_THEME_PACKS,
  mergeXiaAppearanceConfig,
  readXiaAppearance,
  resolveThemePack,
} from "@/shared/styles/xiadown-theme";
export type {
  XiaAccentMode,
  XiaAppearanceSettings,
  XiaSidebarStyle,
  XiaThemePack,
  XiaThemePackId,
} from "@/shared/styles/xiadown-theme";


function buildText(language: SupportedLanguage) {
  return {
    locale: language,
    appName: t("xiadown.appName", language),
    productSubtitle: t("xiadown.productSubtitle", language),
    website: t("xiadown.website", language),
    themePacks: {
      graphite: {
        label: t("xiadown.themePacks.graphite.label", language),
        description: t("xiadown.themePacks.graphite.description", language),
      },
      citrus: {
        label: t("xiadown.themePacks.citrus.label", language),
        description: t("xiadown.themePacks.citrus.description", language),
      },
      pixel: {
        label: t("xiadown.themePacks.pixel.label", language),
        description: t("xiadown.themePacks.pixel.description", language),
      },
      tape: {
        label: t("xiadown.themePacks.tape.label", language),
        description: t("xiadown.themePacks.tape.description", language),
      },
      teal: {
        label: t("xiadown.themePacks.teal.label", language),
        description: t("xiadown.themePacks.teal.description", language),
      },
      cloud: {
        label: t("xiadown.themePacks.cloud.label", language),
        description: t("xiadown.themePacks.cloud.description", language),
      },
      damson: {
        label: t("xiadown.themePacks.damson.label", language),
        description: t("xiadown.themePacks.damson.description", language),
      },
      fuchsia: {
        label: t("xiadown.themePacks.fuchsia.label", language),
        description: t("xiadown.themePacks.fuchsia.description", language),
      },
      cobalt: {
        label: t("xiadown.themePacks.cobalt.label", language),
        description: t("xiadown.themePacks.cobalt.description", language),
      },
      terracotta: {
        label: t("xiadown.themePacks.terracotta.label", language),
        description: t("xiadown.themePacks.terracotta.description", language),
      },
      lavender: {
        label: t("xiadown.themePacks.lavender.label", language),
        description: t("xiadown.themePacks.lavender.description", language),
      },
      nocturne: {
        label: t("xiadown.themePacks.nocturne.label", language),
        description: t("xiadown.themePacks.nocturne.description", language),
      },
    },
    library: {
      status: {
        queued: t("library.status.queued", language),
        running: t("library.status.running", language),
        succeeded: t("library.status.succeeded", language),
        failed: t("library.status.failed", language),
        canceled: t("library.status.canceled", language),
      },
      progress: {
        starting: t("library.progress.starting", language),
        preparing: t("library.progress.preparing", language),
        fetchingMetadata: t("library.progress.fetchingMetadata", language),
        transcoding: t("library.progress.transcoding", language),
        downloading: t("library.progress.downloading", language),
        downloadingVideo: t("library.progress.downloadingVideo", language),
        downloadingAudio: t("library.progress.downloadingAudio", language),
        downloadingSubtitles: t("library.progress.downloadingSubtitles", language),
        downloadingThumbnail: t("library.progress.downloadingThumbnail", language),
        muxing: t("library.progress.muxing", language),
        cleaningUp: t("library.progress.cleaningUp", language),
        postProcessing: t("library.progress.postProcessing", language),
      },
      progressDetail: {
        preparingDownload: t("library.progressDetail.preparingDownload", language),
        preparingFfmpegTranscode: t(
          "library.progressDetail.preparingFfmpegTranscode",
          language,
        ),
        ffmpegRenderingOutput: t(
          "library.progressDetail.ffmpegRenderingOutput",
          language,
        ),
        ffmpegTranscodeQueued: t(
          "library.progressDetail.ffmpegTranscodeQueued",
          language,
        ),
        ffmpegTranscodeCompleted: t(
          "library.progressDetail.ffmpegTranscodeCompleted",
          language,
        ),
        resumeRequested: t("library.progressDetail.resumeRequested", language),
        downloadCanceled: t("library.progressDetail.downloadCanceled", language),
        transcodeCanceled: t(
          "library.progressDetail.transcodeCanceled",
          language,
        ),
        operationCanceled: t(
          "library.progressDetail.operationCanceled",
          language,
        ),
        operationInterrupted: t(
          "library.progressDetail.operationInterrupted",
          language,
        ),
        downloadFailed: t("library.progressDetail.downloadFailed", language),
        transcodeFailed: t("library.progressDetail.transcodeFailed", language),
        operationFailed: t("library.progressDetail.operationFailed", language),
      },
    },
    views: {
      running: t("xiadown.views.running", language),
      completed: t("xiadown.views.completed", language),
      dreamFM: "Dream.FM",
      connections: t("xiadown.views.connections", language),
      tasks: t("xiadown.views.tasks", language),
      library: t("xiadown.views.library", language),
      files: t("xiadown.views.files", language),
    },
    actions: {
      settings: t("xiadown.actions.settings", language),
      open: t("xiadown.actions.open", language),
      close: t("xiadown.actions.close", language),
      clear: t("xiadown.actions.clear", language),
      cancel: t("xiadown.actions.cancel", language),
      cancelDialog: t("xiadown.actions.cancelDialog", language),
      resume: t("xiadown.actions.resume", language),
      view: t("xiadown.actions.view", language),
      delete: t("xiadown.actions.delete", language),
      deleteItem: t("xiadown.actions.deleteItem", language),
      start: t("xiadown.actions.start", language),
      startTask: t("xiadown.actions.startTask", language),
      next: t("xiadown.actions.next", language),
      back: t("xiadown.actions.back", language),
      installAll: t("xiadown.actions.installAll", language),
      download: t("xiadown.actions.download", language),
      transcode: t("xiadown.actions.transcode", language),
      analyze: t("xiadown.actions.analyze", language),
      createTask: t("xiadown.actions.createTask", language),
      chooseFile: t("xiadown.actions.chooseFile", language),
      chooseFolder: t("xiadown.actions.chooseFolder", language),
      reset: t("xiadown.actions.reset", language),
      save: t("xiadown.actions.save", language),
      install: t("xiadown.actions.install", language),
      verify: t("xiadown.actions.verify", language),
      testProxy: t("xiadown.actions.testProxy", language),
      openDirectory: t("xiadown.actions.openDirectory", language),
      checkUpdates: t("xiadown.actions.checkUpdates", language),
      installUpdate: t("xiadown.actions.installUpdate", language),
      restartToApply: t("xiadown.actions.restartToApply", language),
      previous: t("xiadown.actions.previous", language),
      nextTrack: t("xiadown.actions.nextTrack", language),
      pause: t("xiadown.actions.pause", language),
      play: t("xiadown.actions.play", language),
      openSettings: t("xiadown.actions.openSettings", language),
      openLogs: t("xiadown.actions.openLogs", language),
    },
    sidebar: {
      newTask: t("xiadown.sidebar.newTask", language),
      newDownload: t("xiadown.sidebar.newDownload", language),
      newTranscode: t("xiadown.sidebar.newTranscode", language),
      profileHint: t("xiadown.sidebar.profileHint", language),
      openDownloads: t("xiadown.sidebar.openDownloads", language),
      appUpdate: t("xiadown.sidebar.appUpdate", language),
      dependencyUpdate: t("xiadown.sidebar.dependencyUpdate", language),
    },
    spriteStudio: {
      title: t("xiadown.spriteStudio.title", language),
      breadcrumb: t("xiadown.spriteStudio.breadcrumb", language),
      gallery: t("xiadown.spriteStudio.gallery", language),
      localGallery: t("xiadown.spriteStudio.localGallery", language),
      onlineGallery: t("xiadown.spriteStudio.onlineGallery", language),
      localCount: t("xiadown.spriteStudio.localCount", language),
      onlineCount: t("xiadown.spriteStudio.onlineCount", language),
      openLocal: t("xiadown.spriteStudio.openLocal", language),
      openOnline: t("xiadown.spriteStudio.openOnline", language),
      refreshCatalog: t("xiadown.spriteStudio.refreshCatalog", language),
      allCategories: t("xiadown.spriteStudio.allCategories", language),
      searchOnline: t("xiadown.spriteStudio.searchOnline", language),
      onlineSearchResults: t("xiadown.spriteStudio.onlineSearchResults", language),
      onlineEmpty: t("xiadown.spriteStudio.onlineEmpty", language),
      onlineLoadFailed: t("xiadown.spriteStudio.onlineLoadFailed", language),
      installed: t("xiadown.spriteStudio.installed", language),
      installing: t("xiadown.spriteStudio.installing", language),
      downloading: t("xiadown.spriteStudio.downloading", language),
      importing: t("xiadown.spriteStudio.importing", language),
      installSucceeded: t("xiadown.spriteStudio.installSucceeded", language),
      installFailed: t("xiadown.spriteStudio.installFailed", language),
      versionLabel: t("xiadown.spriteStudio.versionLabel", language),
      sizeLabel: t("xiadown.spriteStudio.sizeLabel", language),
      updatedLabel: t("xiadown.spriteStudio.updatedLabel", language),
      importTitle: t("xiadown.spriteStudio.importTitle", language),
      importFailedTitle: t("xiadown.spriteStudio.importFailedTitle", language),
      importErrors: {
        fallback: t("xiadown.spriteStudio.importErrors.fallback", language),
        unsupportedFormat: t("xiadown.spriteStudio.importErrors.unsupportedFormat", language),
        invalidArchive: t("xiadown.spriteStudio.importErrors.invalidArchive", language),
        archiveTooLarge: t("xiadown.spriteStudio.importErrors.archiveTooLarge", language),
        invalidManifest: t("xiadown.spriteStudio.importErrors.invalidManifest", language),
        missingSheet: t("xiadown.spriteStudio.importErrors.missingSheet", language),
        invalidImage: t("xiadown.spriteStudio.importErrors.invalidImage", language),
        notSquare: t("xiadown.spriteStudio.importErrors.notSquare", language),
        tooSmall: t("xiadown.spriteStudio.importErrors.tooSmall", language),
        tooLarge: t("xiadown.spriteStudio.importErrors.tooLarge", language),
      },
      importAction: t("xiadown.settings.sprites.importAction", language),
      generationGuide: {
        action: t("xiadown.spriteStudio.generationGuide.action", language),
        title: t("xiadown.spriteStudio.generationGuide.title", language),
        description: t("xiadown.spriteStudio.generationGuide.description", language),
        tabs: {
          conversation: t("xiadown.spriteStudio.generationGuide.tabs.conversation", language),
          code: t("xiadown.spriteStudio.generationGuide.tabs.code", language),
        },
        clipboardAction: t("xiadown.spriteStudio.generationGuide.clipboardAction", language),
        clipboardSucceeded: t("xiadown.spriteStudio.generationGuide.clipboardSucceeded", language),
        clipboardFailed: t("xiadown.spriteStudio.generationGuide.clipboardFailed", language),
        prompts: {
          conversation: t("xiadown.spriteStudio.generationGuide.prompts.conversation", language),
          code: t("xiadown.spriteStudio.generationGuide.prompts.code", language),
        },
      },
      editTab: t("xiadown.spriteStudio.editTab", language),
      previewTab: t("xiadown.spriteStudio.previewTab", language),
      dragHint: t("xiadown.spriteStudio.dragHint", language),
      readonlyHint: t("xiadown.spriteStudio.readonlyHint", language),
      readonly: t("xiadown.spriteStudio.readonly", language),
      saving: t("xiadown.spriteStudio.saving", language),
      saved: t("xiadown.spriteStudio.saved", language),
      saveError: t("xiadown.spriteStudio.saveError", language),
      saveFailed: t("xiadown.spriteStudio.saveFailed", language),
      empty: t("xiadown.spriteStudio.empty", language),
      verticalLine: t("xiadown.spriteStudio.verticalLine", language),
      horizontalLine: t("xiadown.spriteStudio.horizontalLine", language),
      sheetSize: t("xiadown.spriteStudio.sheetSize", language),
      gridSize: t("xiadown.spriteStudio.gridSize", language),
      firstFrame: t("xiadown.spriteStudio.firstFrame", language),
      resetEqual: t("xiadown.spriteStudio.resetEqual", language),
      animations: {
        greeting: t("xiadown.spriteStudio.animations.greeting", language),
        snoring: t("xiadown.spriteStudio.animations.snoring", language),
        upset: t("xiadown.spriteStudio.animations.upset", language),
        celebrate: t("xiadown.spriteStudio.animations.celebrate", language),
        seeking: t("xiadown.spriteStudio.animations.seeking", language),
        embarrassed: t("xiadown.spriteStudio.animations.embarrassed", language),
        working: t("xiadown.spriteStudio.animations.working", language),
        listeningToMusic: t("xiadown.spriteStudio.animations.listeningToMusic", language),
      },
    },
    running: {
      title: t("xiadown.running.title", language),
      emptyAction: t("xiadown.running.emptyAction", language),
      emptyTitle: t("xiadown.running.emptyTitle", language),
      empty: t("xiadown.running.empty", language),
      loading: t("xiadown.running.loading", language),
      overviewTitle: t("xiadown.running.overviewTitle", language),
      taskCount: t("xiadown.running.taskCount", language),
      overallProgress: t("xiadown.running.overallProgress", language),
      throughput: t("xiadown.running.throughput", language),
      elapsed: t("xiadown.running.elapsed", language),
      runningCount: t("xiadown.running.runningCount", language),
      queuedCount: t("xiadown.running.queuedCount", language),
      downloadSpeed: t("xiadown.running.downloadSpeed", language),
      transcodeSpeed: t("xiadown.running.transcodeSpeed", language),
      runningCountLine: t("xiadown.running.runningCountLine", language),
      queuedCountLine: t("xiadown.running.queuedCountLine", language),
      downloadSpeedLine: t("xiadown.running.downloadSpeedLine", language),
      transcodeSpeedLine: t("xiadown.running.transcodeSpeedLine", language),
      rangeLine: t("xiadown.running.rangeLine", language),
      percentLabel: t("xiadown.running.percentLabel", language),
      unavailable: t("xiadown.running.unavailable", language),
      separator: t("xiadown.running.separator", language),
      summarySeparator: t("xiadown.running.summarySeparator", language),
      units: {
        bytesPerSecond: t("xiadown.running.units.bytesPerSecond", language),
        framesPerSecond: t(
          "xiadown.running.units.framesPerSecond",
          language,
        ),
        speedFactor: t("xiadown.running.units.speedFactor", language),
      },
      progressFallback: t("xiadown.running.progressFallback", language),
      downloadBadge: t("xiadown.running.downloadBadge", language),
      transcodeBadge: t("xiadown.running.transcodeBadge", language),
      source: t("xiadown.running.source", language),
      createdAt: t("xiadown.running.createdAt", language),
      localSource: t("xiadown.running.localSource", language),
      stage: t("xiadown.running.stage", language),
      status: t("xiadown.running.status", language),
      eta: t("xiadown.running.eta", language),
      cancelConfirmTitle: t("xiadown.running.cancelConfirmTitle", language),
      cancelConfirmDescription: t(
        "xiadown.running.cancelConfirmDescription",
        language,
      ),
      stageLabels: {
        starting: t("xiadown.running.stageLabels.starting", language),
        preparing: t("xiadown.running.stageLabels.preparing", language),
        fetchingMetadata: t(
          "xiadown.running.stageLabels.fetchingMetadata",
          language,
        ),
        transcoding: t("xiadown.running.stageLabels.transcoding", language),
        downloading: t("xiadown.running.stageLabels.downloading", language),
        downloadingVideo: t(
          "xiadown.running.stageLabels.downloadingVideo",
          language,
        ),
        downloadingAudio: t(
          "xiadown.running.stageLabels.downloadingAudio",
          language,
        ),
        downloadingSubtitles: t(
          "xiadown.running.stageLabels.downloadingSubtitles",
          language,
        ),
        downloadingThumbnail: t(
          "xiadown.running.stageLabels.downloadingThumbnail",
          language,
        ),
        muxing: t("xiadown.running.stageLabels.muxing", language),
        cleaningUp: t("xiadown.running.stageLabels.cleaningUp", language),
        postProcessing: t(
          "xiadown.running.stageLabels.postProcessing",
          language,
        ),
        queued: t("xiadown.running.stageLabels.queued", language),
        running: t("xiadown.running.stageLabels.running", language),
        completed: t("xiadown.running.stageLabels.completed", language),
        failed: t("xiadown.running.stageLabels.failed", language),
        canceled: t("xiadown.running.stageLabels.canceled", language),
      },
    },
    completed: {
      title: t("xiadown.completed.title", language),
      emptyTasks: t("xiadown.completed.emptyTasks", language),
      emptyLibrary: t("xiadown.completed.emptyLibrary", language),
      emptyFiles: t("xiadown.completed.emptyFiles", language),
      detailEmpty: t("xiadown.completed.detailEmpty", language),
      records: t("xiadown.completed.records", language),
      outputs: t("xiadown.completed.outputs", language),
      info: t("xiadown.completed.info", language),
      taskDetail: t("xiadown.completed.taskDetail", language),
      taskDtoTitle: t("xiadown.completed.taskDtoTitle", language),
      openTaskDto: t("xiadown.completed.openTaskDto", language),
      copyDownloadUrl: t("xiadown.completed.copyDownloadUrl", language),
      downloadUrlCopied: t("xiadown.completed.downloadUrlCopied", language),
      copyFailed: t("xiadown.completed.copyFailed", language),
      taskDataFields: {
        name: t("xiadown.completed.taskDataFields.name", language),
        url: t("xiadown.completed.taskDataFields.url", language),
        inputPath: t("xiadown.completed.taskDataFields.inputPath", language),
        format: t("xiadown.completed.taskDataFields.format", language),
        preset: t("xiadown.completed.taskDataFields.preset", language),
        videoCodec: t("xiadown.completed.taskDataFields.videoCodec", language),
        audioCodec: t("xiadown.completed.taskDataFields.audioCodec", language),
        qualityMode: t("xiadown.completed.taskDataFields.qualityMode", language),
        scale: t("xiadown.completed.taskDataFields.scale", language),
        deleteSourceFileAfterTranscode: t(
          "xiadown.completed.taskDataFields.deleteSourceFileAfterTranscode",
          language,
        ),
        enabled: t("xiadown.completed.taskDataFields.enabled", language),
        kind: t("xiadown.completed.taskDataFields.kind", language),
        status: t("xiadown.completed.taskDataFields.status", language),
        failureReason: t(
          "xiadown.completed.taskDataFields.failureReason",
          language,
        ),
        errorCode: t("xiadown.completed.taskDataFields.errorCode", language),
        domain: t("xiadown.completed.taskDataFields.domain", language),
        platform: t("xiadown.completed.taskDataFields.platform", language),
        uploader: t("xiadown.completed.taskDataFields.uploader", language),
        publishTime: t(
          "xiadown.completed.taskDataFields.publishTime",
          language,
        ),
        startedAt: t("xiadown.completed.taskDataFields.startedAt", language),
        finishedAt: t("xiadown.completed.taskDataFields.finishedAt", language),
        createdAt: t("xiadown.completed.taskDataFields.createdAt", language),
      },
      fileDetail: t("xiadown.completed.fileDetail", language),
      searchTasks: t("xiadown.completed.searchTasks", language),
      searchFiles: t("xiadown.completed.searchFiles", language),
      searchFilter: t("xiadown.completed.searchFilter", language),
      total: t("xiadown.completed.total", language),
      taskCountLabel: t("xiadown.completed.taskCountLabel", language),
      fileCountLabel: t("xiadown.completed.fileCountLabel", language),
      perPage: t("xiadown.completed.perPage", language),
      itemUnit: t("xiadown.completed.itemUnit", language),
      page: t("xiadown.completed.page", language),
      pageSuffix: t("xiadown.completed.pageSuffix", language),
      taskStatus: t("xiadown.completed.taskStatus", language),
      source: t("xiadown.completed.source", language),
      fileType: t("xiadown.completed.fileType", language),
      fileFormat: t("xiadown.completed.fileFormat", language),
      fileInfo: t("xiadown.completed.fileInfo", language),
      selectFiles: t("xiadown.completed.selectFiles", language),
      verifyFiles: t("xiadown.completed.verifyFiles", language),
      clearMissingFiles: t("xiadown.completed.clearMissingFiles", language),
      verifyFilesMissingToast: t(
        "xiadown.completed.verifyFilesMissingToast",
        language,
      ),
      verifyFilesValidToast: t(
        "xiadown.completed.verifyFilesValidToast",
        language,
      ),
      clearMissingFilesRemovedToast: t(
        "xiadown.completed.clearMissingFilesRemovedToast",
        language,
      ),
      clearMissingFilesNoneToast: t(
        "xiadown.completed.clearMissingFilesNoneToast",
        language,
      ),
      fileMaintenanceFailed: t(
        "xiadown.completed.fileMaintenanceFailed",
        language,
      ),
      selectionSummary: t("xiadown.completed.selectionSummary", language),
      selectionUnit: t("xiadown.completed.selectionUnit", language),
      lineUnit: t("xiadown.completed.lineUnit", language),
      lineCount: t("xiadown.completed.lineCount", language),
      deleteFiles: t("xiadown.completed.deleteFiles", language),
      deleteTaskTitle: t("xiadown.completed.deleteTaskTitle", language),
      deleteTasksTitle: t("xiadown.completed.deleteTasksTitle", language),
      deleteFileTitle: t("xiadown.completed.deleteFileTitle", language),
      deleteFilesTitle: t("xiadown.completed.deleteFilesTitle", language),
      deleteTaskMessage: t("xiadown.completed.deleteTaskMessage", language),
      deleteTasksMessage: t("xiadown.completed.deleteTasksMessage", language),
      deleteFileMessage: t("xiadown.completed.deleteFileMessage", language),
      deleteFilesMessage: t("xiadown.completed.deleteFilesMessage", language),
      previousPage: t("xiadown.completed.previousPage", language),
      nextPage: t("xiadown.completed.nextPage", language),
      previewPlay: t("xiadown.completed.previewPlay", language),
      previewPause: t("xiadown.completed.previewPause", language),
      previewSeek: t("xiadown.completed.previewSeek", language),
      previewMute: t("xiadown.completed.previewMute", language),
      previewUnmute: t("xiadown.completed.previewUnmute", language),
      previewVolume: t("xiadown.completed.previewVolume", language),
      previewWindowFullscreen: t(
        "xiadown.completed.previewWindowFullscreen",
        language,
      ),
      previewWindowRestore: t(
        "xiadown.completed.previewWindowRestore",
        language,
      ),
      previewEnterFullscreen: t(
        "xiadown.completed.previewEnterFullscreen",
        language,
      ),
      previewExitFullscreen: t(
        "xiadown.completed.previewExitFullscreen",
        language,
      ),
      noPreview: t("xiadown.completed.noPreview", language),
      noSelectedTask: t("xiadown.completed.noSelectedTask", language),
      noSelectedFile: t("xiadown.completed.noSelectedFile", language),
      taskNoFiles: t("xiadown.completed.taskNoFiles", language),
      updatedAt: t("xiadown.completed.updatedAt", language),
      videoCount: t("xiadown.completed.videoCount", language),
      subtitleCount: t("xiadown.completed.subtitleCount", language),
      imageCount: t("xiadown.completed.imageCount", language),
      typeVideo: t("xiadown.completed.typeVideo", language),
      typeAudio: t("xiadown.completed.typeAudio", language),
      typeSubtitle: t("xiadown.completed.typeSubtitle", language),
      typeImage: t("xiadown.completed.typeImage", language),
      typeOther: t("xiadown.completed.typeOther", language),
      resolution: t("xiadown.completed.resolution", language),
      frameRate: t("xiadown.completed.frameRate", language),
      duration: t("xiadown.completed.duration", language),
      channels: t("xiadown.completed.channels", language),
      dpi: t("xiadown.completed.dpi", language),
      codec: t("xiadown.completed.codec", language),
      bitrate: t("xiadown.completed.bitrate", language),
      videoBitrate: t("xiadown.completed.videoBitrate", language),
      audioBitrate: t("xiadown.completed.audioBitrate", language),
      fileSize: t("xiadown.completed.fileSize", language),
      originalFormat: t("xiadown.completed.originalFormat", language),
      succeeded: t("xiadown.completed.succeeded", language),
      failed: t("xiadown.completed.failed", language),
      canceled: t("xiadown.completed.canceled", language),
    },
    welcome: {
      title: t("xiadown.welcome.title", language),
      subtitle: t("xiadown.welcome.subtitle", language),
      language: t("xiadown.welcome.language", language),
      proxy: t("xiadown.welcome.proxy", language),
      dependencies: t("xiadown.welcome.dependencies", language),
      dependencyStatus: t("xiadown.welcome.dependencyStatus", language),
      latestVersion: t("xiadown.welcome.latestVersion", language),
    },
    settings: {
      title: t("xiadown.settings.title", language),
      tabs: {
        general: t("xiadown.settings.tabs.general", language),
        appearance: t("xiadown.settings.tabs.appearance", language),
        sprites: t("xiadown.settings.tabs.sprites", language),
        dependencies: t("xiadown.settings.tabs.dependencies", language),
        about: t("xiadown.settings.tabs.about", language),
      },
      startup: t("xiadown.settings.startup", language),
      tray: t("xiadown.settings.tray", language),
      menuBar: t("xiadown.settings.menuBar", language),
      downloadDirectory: t("xiadown.settings.downloadDirectory", language),
      language: t("xiadown.settings.language", language),
      logLevel: t("xiadown.settings.logLevel", language),
      themePack: t("xiadown.settings.themePack", language),
      accent: t("xiadown.settings.accent", language),
      accentColor: t("xiadown.settings.accentColor", language),
      fontFamily: t("xiadown.settings.fontFamily", language),
      fontSize: t("xiadown.settings.fontSize", language),
      colorScheme: t("xiadown.settings.colorScheme", language),
      appearanceMode: t("xiadown.settings.appearanceMode", language),
      sidebarStyle: t("xiadown.settings.sidebarStyle", language),
      systemProxy: t("xiadown.settings.systemProxy", language),
      manualProxy: t("xiadown.settings.manualProxy", language),
      noProxy: t("xiadown.settings.noProxy", language),
      proxy: t("xiadown.settings.proxy", language),
      host: t("xiadown.settings.host", language),
      port: t("xiadown.settings.port", language),
      username: t("xiadown.settings.username", language),
      password: t("xiadown.settings.password", language),
      timeout: t("xiadown.settings.timeout", language),
      scheme: t("xiadown.settings.scheme", language),
      noProxyList: t("xiadown.settings.noProxyList", language),
      status: t("xiadown.settings.status", language),
      checking: t("xiadown.settings.checking", language),
      notConfigured: t("xiadown.settings.notConfigured", language),
      unavailable: t("xiadown.settings.unavailable", language),
      systemSource: t("xiadown.settings.systemSource", language),
      vpnSource: t("xiadown.settings.vpnSource", language),
      editProxy: t("xiadown.settings.editProxy", language),
      proxyDialogTitle: t("xiadown.settings.proxyDialogTitle", language),
      proxyDialogHint: t("xiadown.settings.proxyDialogHint", language),
      aboutText: t("xiadown.settings.aboutText", language),
      otherSoftware: t("xiadown.settings.otherSoftware", language),
      generalDescription: t("xiadown.settings.generalDescription", language),
      appearanceDescription: t(
        "xiadown.settings.appearanceDescription",
        language,
      ),
      proxyDescription: t("xiadown.settings.proxyDescription", language),
      menuBarOptions: {
        always: t("xiadown.settings.menuBarOptions.always", language),
        whenRunning: t("xiadown.settings.menuBarOptions.whenRunning", language),
        never: t("xiadown.settings.menuBarOptions.never", language),
      },
      colorSchemeOptions: {
        default: t("xiadown.settings.colorSchemeOptions.default", language),
        contrast: t("xiadown.settings.colorSchemeOptions.contrast", language),
        slate: t("xiadown.settings.colorSchemeOptions.slate", language),
        warm: t("xiadown.settings.colorSchemeOptions.warm", language),
      },
      sidebarStyleOptions: {
        glass: t("xiadown.settings.sidebarStyleOptions.glass", language),
        contrast: t("xiadown.settings.sidebarStyleOptions.contrast", language),
        pixel: t("xiadown.settings.sidebarStyleOptions.pixel", language),
      },
      accentOptions: {
        theme: t("xiadown.settings.accentOptions.theme", language),
        color: t("xiadown.settings.accentOptions.color", language),
      },
      systemProxyEmpty: t("xiadown.settings.systemProxyEmpty", language),
      proxyTestSucceeded: t("xiadown.settings.proxyTestSucceeded", language),
      proxyTestFailed: t("xiadown.settings.proxyTestFailed", language),
      sprites: {
        builtinTitle: t("xiadown.settings.sprites.builtinTitle", language),
        builtinHint: t("xiadown.settings.sprites.builtinHint", language),
        importTitle: t("xiadown.settings.sprites.importTitle", language),
        importHint: t("xiadown.settings.sprites.importHint", language),
        importPreviewHint: t(
          "xiadown.settings.sprites.importPreviewHint",
          language,
        ),
        importAction: t("xiadown.settings.sprites.importAction", language),
        importSucceeded: t(
          "xiadown.settings.sprites.importSucceeded",
          language,
        ),
        customTitle: t("xiadown.settings.sprites.customTitle", language),
        customHint: t("xiadown.settings.sprites.customHint", language),
        editorTitle: t("xiadown.settings.sprites.editorTitle", language),
        editorHint: t("xiadown.settings.sprites.editorHint", language),
        emptyBuiltin: t("xiadown.settings.sprites.emptyBuiltin", language),
        emptyCustom: t("xiadown.settings.sprites.emptyCustom", language),
        chooseFile: t("xiadown.settings.sprites.chooseFile", language),
        changeFile: t("xiadown.settings.sprites.changeFile", language),
        selectedFile: t("xiadown.settings.sprites.selectedFile", language),
        currentSprite: t("xiadown.settings.sprites.currentSprite", language),
        operation: t("xiadown.settings.sprites.operation", language),
        more: t("xiadown.settings.sprites.more", language),
        editAction: t("xiadown.settings.sprites.editAction", language),
        filePlaceholder: t(
          "xiadown.settings.sprites.filePlaceholder",
          language,
        ),
        name: t("xiadown.settings.sprites.name", language),
        namePlaceholder: t(
          "xiadown.settings.sprites.namePlaceholder",
          language,
        ),
        description: t("xiadown.settings.sprites.description", language),
        descriptionPlaceholder: t(
          "xiadown.settings.sprites.descriptionPlaceholder",
          language,
        ),
        author: t("xiadown.settings.sprites.author", language),
        authorPlaceholder: t(
          "xiadown.settings.sprites.authorPlaceholder",
          language,
        ),
        version: t("xiadown.settings.sprites.version", language),
        setDefaultAction: t(
          "xiadown.settings.sprites.setDefaultAction",
          language,
        ),
        setDefaultSucceeded: t(
          "xiadown.settings.sprites.setDefaultSucceeded",
          language,
        ),
        useSprite: t("xiadown.settings.sprites.useSprite", language),
        current: t("xiadown.settings.sprites.current", language),
        invalid: t("xiadown.settings.sprites.invalid", language),
        exportTitle: t("xiadown.settings.sprites.exportTitle", language),
        exportAction: t("xiadown.settings.sprites.exportAction", language),
        exportSucceeded: t(
          "xiadown.settings.sprites.exportSucceeded",
          language,
        ),
        saveSucceeded: t("xiadown.settings.sprites.saveSucceeded", language),
        deleteAction: t("xiadown.settings.sprites.deleteAction", language),
        deleteTitle: t("xiadown.settings.sprites.deleteTitle", language),
        deleteMessage: t("xiadown.settings.sprites.deleteMessage", language),
        deleteSucceeded: t(
          "xiadown.settings.sprites.deleteSucceeded",
          language,
        ),
        showMore: t("xiadown.settings.sprites.showMore", language),
        showLess: t("xiadown.settings.sprites.showLess", language),
        specHint: t("xiadown.settings.sprites.specHint", language),
      },
    },
    dependencies: {
      title: t("xiadown.dependencies.title", language),
      subtitle: t("xiadown.dependencies.subtitle", language),
      installed: t("xiadown.dependencies.installed", language),
      missing: t("xiadown.dependencies.missing", language),
      invalid: t("xiadown.dependencies.invalid", language),
      idle: t("xiadown.dependencies.idle", language),
      latestVersion: t("xiadown.dependencies.latestVersion", language),
      currentVersion: t("xiadown.dependencies.currentVersion", language),
      execPath: t("xiadown.dependencies.execPath", language),
      noRemoteVersionInfo: t(
        "xiadown.dependencies.noRemoteVersionInfo",
        language,
      ),
      reinstall: t("xiadown.dependencies.reinstall", language),
      downloading: t("xiadown.dependencies.downloading", language),
      extracting: t("xiadown.dependencies.extracting", language),
      verifying: t("xiadown.dependencies.verifying", language),
      installing: t("xiadown.dependencies.installing", language),
      missingDependency: t("xiadown.dependencies.missingDependency", language),
    },
    dialogs: {
      downloadTitle: t("xiadown.dialogs.downloadTitle", language),
      transcodeTitle: t("xiadown.dialogs.transcodeTitle", language),
      dependenciesRequiredTitle: t(
        "xiadown.dialogs.dependenciesRequiredTitle",
        language,
      ),
      dependenciesRequiredDescription: t(
        "xiadown.dialogs.dependenciesRequiredDescription",
        language,
      ),
      url: "URL",
      downloadPlaceholder: t("xiadown.dialogs.downloadPlaceholder", language),
      requestDownload: t("xiadown.dialogs.requestDownload", language),
      quickMode: t("xiadown.dialogs.quickMode", language),
      customMode: t("xiadown.dialogs.customMode", language),
      preset: t("xiadown.dialogs.preset", language),
      format: t("xiadown.dialogs.format", language),
      formatGroupVideo: t("xiadown.dialogs.formatGroupVideo", language),
      formatGroupAudio: t("xiadown.dialogs.formatGroupAudio", language),
      quality: t("xiadown.dialogs.quality", language),
      qualityBest: t("xiadown.dialogs.qualityBest", language),
      qualityAudio: t("xiadown.dialogs.qualityAudio", language),
      selectFormat: t("xiadown.dialogs.selectFormat", language),
      size: t("xiadown.dialogs.size", language),
      container: t("xiadown.dialogs.container", language),
      codec: t("xiadown.dialogs.codec", language),
      scaleOriginal: t("xiadown.dialogs.scaleOriginal", language),
      scaleCustom: t("xiadown.dialogs.scaleCustom", language),
      subtitles: t("xiadown.dialogs.subtitles", language),
      noSubtitle: t("xiadown.dialogs.noSubtitle", language),
      noTranscode: t("xiadown.dialogs.noTranscode", language),
      keepOnlyTranscodedFile: t(
        "xiadown.dialogs.keepOnlyTranscodedFile",
        language,
      ),
      parse: t("xiadown.dialogs.parse", language),
      parseAgain: t("xiadown.dialogs.parseAgain", language),
      parseFailedWithoutConnector: t(
        "xiadown.dialogs.parseFailedWithoutConnector",
        language,
      ),
      parseFailedWithConnector: t(
        "xiadown.dialogs.parseFailedWithConnector",
        language,
      ),
      useConnector: t("xiadown.dialogs.useConnector", language),
      connectorAvailable: t("xiadown.dialogs.connectorAvailable", language),
      connectorUnavailable: t("xiadown.dialogs.connectorUnavailable", language),
      modifyLink: t("xiadown.dialogs.modifyLink", language),
      modifyFile: t("xiadown.dialogs.modifyFile", language),
      path: t("xiadown.dialogs.path", language),
      fileAddress: t("xiadown.dialogs.fileAddress", language),
      nameHint: t("xiadown.dialogs.nameHint", language),
    },
    dreamFm: {
      title: "Dream.FM",
      subtitle: t("xiadown.dreamFm.subtitle", language),
      live: t("xiadown.dreamFm.live", language),
      online: t("xiadown.dreamFm.online", language),
      local: t("xiadown.dreamFm.local", language),
      localEmpty: t("xiadown.dreamFm.localEmpty", language),
      localEmptyPrompt: t("xiadown.dreamFm.localEmptyPrompt", language),
      localEmptyAction: t("xiadown.dreamFm.localEmptyAction", language),
      localLoading: t("xiadown.dreamFm.localLoading", language),
      localRefresh: t("xiadown.dreamFm.localRefresh", language),
      localClearMissing: t("xiadown.dreamFm.localClearMissing", language),
      randomStation: t("xiadown.dreamFm.randomStation", language),
      searchLive: t("xiadown.dreamFm.searchLive", language),
      searchOnline: t("xiadown.dreamFm.searchOnline", language),
      searchLocal: t("xiadown.dreamFm.searchLocal", language),
      searchSongs: t("xiadown.dreamFm.searchSongs", language),
      searchArtists: t("xiadown.dreamFm.searchArtists", language),
      searchPlaylists: t("xiadown.dreamFm.searchPlaylists", language),
      sourceHome: t("xiadown.dreamFm.sourceHome", language),
      sourceExplore: t("xiadown.dreamFm.sourceExplore", language),
      sourceCharts: t("xiadown.dreamFm.sourceCharts", language),
      sourceMoods: t("xiadown.dreamFm.sourceMoods", language),
      sourceNew: t("xiadown.dreamFm.sourceNew", language),
      sourcePodcasts: t("xiadown.dreamFm.sourcePodcasts", language),
      sourceHistory: t("xiadown.dreamFm.sourceHistory", language),
      groupLive: t("xiadown.dreamFm.groupLive", language),
      liveStations: t("xiadown.dreamFm.liveStations", language),
      liveLoading: t("xiadown.dreamFm.liveLoading", language),
      liveUnavailable: t("xiadown.dreamFm.liveUnavailable", language),
      liveEmpty: t("xiadown.dreamFm.liveEmpty", language),
      retry: t("xiadown.dreamFm.retry", language),
      groupLibrary: t("xiadown.dreamFm.groupLibrary", language),
      libraryArtists: t("xiadown.dreamFm.libraryArtists", language),
      libraryPodcasts: t("xiadown.dreamFm.libraryPodcasts", language),
      likedMusic: t("xiadown.dreamFm.likedMusic", language),
      groupCategories: t("xiadown.dreamFm.groupCategories", language),
      groupArtists: t("xiadown.dreamFm.groupArtists", language),
      groupPlaylist: t("xiadown.dreamFm.groupPlaylist", language),
      groupRecommendations: t("xiadown.dreamFm.groupRecommendations", language),
      groupRadio: t("xiadown.dreamFm.groupRadio", language),
      shelfQuickPicks: t("xiadown.dreamFm.shelfQuickPicks", language),
      shelfListenAgain: t("xiadown.dreamFm.shelfListenAgain", language),
      shelfMixedForYou: t("xiadown.dreamFm.shelfMixedForYou", language),
      shelfFeaturedPlaylists: t("xiadown.dreamFm.shelfFeaturedPlaylists", language),
      shelfVideoCharts: t("xiadown.dreamFm.shelfVideoCharts", language),
      shelfTopSongs: t("xiadown.dreamFm.shelfTopSongs", language),
      shelfTopMusicVideos: t("xiadown.dreamFm.shelfTopMusicVideos", language),
      shelfTopArtists: t("xiadown.dreamFm.shelfTopArtists", language),
      shelfTrending: t("xiadown.dreamFm.shelfTrending", language),
      shelfNewAlbums: t("xiadown.dreamFm.shelfNewAlbums", language),
      shelfNewSingles: t("xiadown.dreamFm.shelfNewSingles", language),
      shelfNewVideos: t("xiadown.dreamFm.shelfNewVideos", language),
      shelfNewReleases: t("xiadown.dreamFm.shelfNewReleases", language),
      shelfMoodsAndGenres: t("xiadown.dreamFm.shelfMoodsAndGenres", language),
      liveBadge: t("xiadown.dreamFm.liveBadge", language),
      liveStatusChecking: t("xiadown.dreamFm.liveStatusChecking", language),
      liveStatusLive: t("xiadown.dreamFm.liveStatusLive", language),
      liveStatusOffline: t("xiadown.dreamFm.liveStatusOffline", language),
      liveStatusUpcoming: t("xiadown.dreamFm.liveStatusUpcoming", language),
      liveStatusUnavailable: t("xiadown.dreamFm.liveStatusUnavailable", language),
      liveStatusUnknown: t("xiadown.dreamFm.liveStatusUnknown", language),
      adBadge: t("xiadown.dreamFm.adBadge", language),
      skipAd: t("xiadown.dreamFm.skipAd", language),
      browse: t("xiadown.dreamFm.browse", language),
      upNext: t("xiadown.dreamFm.upNext", language),
      play: t("xiadown.dreamFm.play", language),
      pause: t("xiadown.dreamFm.pause", language),
      loading: t("xiadown.dreamFm.loading", language),
      idleStatus: t("xiadown.dreamFm.idleStatus", language),
      nowPlaying: t("xiadown.dreamFm.nowPlaying", language),
      playingStatus: t("xiadown.dreamFm.playingStatus", language),
      pausedStatus: t("xiadown.dreamFm.pausedStatus", language),
      loadingStatus: t("xiadown.dreamFm.loadingStatus", language),
      errorStatus: t("xiadown.dreamFm.errorStatus", language),
      errorCodeLabel: t("xiadown.dreamFm.errorCodeLabel", language),
      idleSubtitle: t("xiadown.dreamFm.idleSubtitle", language),
      previous: t("xiadown.dreamFm.previous", language),
      next: t("xiadown.dreamFm.next", language),
      playbackMode: t("xiadown.dreamFm.playbackMode", language),
      playModeOrder: t("xiadown.dreamFm.playModeOrder", language),
      playModeShuffle: t("xiadown.dreamFm.playModeShuffle", language),
      playModeRepeat: t("xiadown.dreamFm.playModeRepeat", language),
      mute: t("xiadown.dreamFm.mute", language),
      unmute: t("xiadown.dreamFm.unmute", language),
      volume: t("xiadown.dreamFm.volume", language),
      seek: t("xiadown.dreamFm.seek", language),
      favorite: t("xiadown.dreamFm.favorite", language),
      favoriteUnavailable: t("xiadown.dreamFm.favoriteUnavailable", language),
      selectStation: t("xiadown.dreamFm.selectStation", language),
      collapseList: t("xiadown.dreamFm.collapseList", language),
      openList: t("xiadown.dreamFm.openList", language),
      onlineHint: t("xiadown.dreamFm.onlineHint", language),
      onlineLoading: t("xiadown.dreamFm.onlineLoading", language),
      onlineUnavailable: t("xiadown.dreamFm.onlineUnavailable", language),
      onlineConnectionPrompt: t(
        "xiadown.dreamFm.onlineConnectionPrompt",
        language,
      ),
      onlineAuthRequired: t("xiadown.dreamFm.onlineAuthRequired", language),
      onlineAuthExpired: t("xiadown.dreamFm.onlineAuthExpired", language),
      onlineNetworkUnavailable: t(
        "xiadown.dreamFm.onlineNetworkUnavailable",
        language,
      ),
      onlineServiceUnavailable: t(
        "xiadown.dreamFm.onlineServiceUnavailable",
        language,
      ),
      openConnections: t("xiadown.dreamFm.openConnections", language),
      refresh: t("xiadown.dreamFm.refresh", language),
      contentEmpty: t("xiadown.dreamFm.contentEmpty", language),
      onlineEmpty: t("xiadown.dreamFm.onlineEmpty", language),
      searchLoading: t("xiadown.dreamFm.searchLoading", language),
      searchUnavailable: t("xiadown.dreamFm.searchUnavailable", language),
      searchEmpty: t("xiadown.dreamFm.searchEmpty", language),
      loadMore: t("xiadown.dreamFm.loadMore", language),
      playAll: t("xiadown.dreamFm.playAll", language),
      shuffleAll: t("xiadown.dreamFm.shuffleAll", language),
      clearQueue: t("xiadown.dreamFm.clearQueue", language),
      removeFromQueue: t("xiadown.dreamFm.removeFromQueue", language),
      airPlay: t("xiadown.dreamFm.airPlay", language),
      video: t("xiadown.dreamFm.video", language),
      noVideo: t("xiadown.dreamFm.noVideo", language),
      lyrics: t("xiadown.dreamFm.lyrics", language),
      lyricsEmpty: t("xiadown.dreamFm.lyricsEmpty", language),
      more: t("xiadown.dreamFm.more", language),
      openPage: t("xiadown.dreamFm.openPage", language),
      copyLink: t("xiadown.dreamFm.copyLink", language),
      linkCopied: t("xiadown.dreamFm.linkCopied", language),
      artistShuffle: t("xiadown.dreamFm.artistShuffle", language),
      artistMix: t("xiadown.dreamFm.artistMix", language),
      artistSubscribe: t("xiadown.dreamFm.artistSubscribe", language),
      artistUnsubscribe: t("xiadown.dreamFm.artistUnsubscribe", language),
      artistLoading: t("xiadown.dreamFm.artistLoading", language),
      artistUnavailable: t("xiadown.dreamFm.artistUnavailable", language),
      artistEmpty: t("xiadown.dreamFm.artistEmpty", language),
      playlistLoading: t("xiadown.dreamFm.playlistLoading", language),
      playlistEmpty: t("xiadown.dreamFm.playlistEmpty", language),
      upNextEmpty: t("xiadown.dreamFm.upNextEmpty", language),
      savePlaylist: t("xiadown.dreamFm.savePlaylist", language),
      removePlaylist: t("xiadown.dreamFm.removePlaylist", language),
      playerUnavailable: t("xiadown.dreamFm.playerUnavailable", language),
    },
    whatsNew: {
      title: t("xiadown.whatsNew.title", language),
      empty: t("xiadown.whatsNew.empty", language),
    },
    about: {
      updateStatus: t("xiadown.about.updateStatus", language),
      currentVersion: t("xiadown.about.currentVersion", language),
      latestVersion: t("xiadown.about.latestVersion", language),
      status: t("xiadown.about.status", language),
      latestOk: t("xiadown.about.latestOk", language),
      latestAvailable: t("xiadown.about.latestAvailable", language),
      latestFailed: t("xiadown.about.latestFailed", language),
      viewChangelog: t("xiadown.about.viewChangelog", language),
      viewReleaseNotes: t("xiadown.about.viewReleaseNotes", language),
      noReleaseNotes: t("xiadown.about.noReleaseNotes", language),
      releaseNotesClose: t("xiadown.about.releaseNotesClose", language),
      checkUpdates: t("xiadown.about.checkUpdates", language),
      recheck: t("xiadown.about.recheck", language),
      downloadAndInstall: t("xiadown.about.downloadAndInstall", language),
      restartAfterUpdate: t("xiadown.about.restartAfterUpdate", language),
      downloading: t("xiadown.about.downloading", language),
      installing: t("xiadown.about.installing", language),
      craftedBy: t("xiadown.about.craftedBy", language),
      contact: t("xiadown.about.contact", language),
      feedback: t("xiadown.about.feedback", language),
      sendFeedback: t("xiadown.about.sendFeedback", language),
      email: t("xiadown.about.email", language),
      twitter: t("xiadown.about.twitter", language),
      website: t("xiadown.about.website", language),
      github: t("xiadown.about.github", language),
      dreamCreator: t("xiadown.about.dreamCreator", language),
      dreamCreatorDescription: t(
        "xiadown.about.dreamCreatorDescription",
        language,
      ),
    },
    common: {
      systemDefault: t("xiadown.common.systemDefault", language),
      current: t("xiadown.common.current", language),
      customColor: t("xiadown.common.customColor", language),
      light: t("xiadown.common.light", language),
      dark: t("xiadown.common.dark", language),
      auto: t("xiadown.common.auto", language),
      followSystem: t("xiadown.common.followSystem", language),
      ready: t("xiadown.common.ready", language),
      unknown: t("xiadown.common.unknown", language),
      browse: t("xiadown.common.browse", language),
      colorOptions: {
        blue: t("xiadown.common.colorOptions.blue", language),
        indigo: t("xiadown.common.colorOptions.indigo", language),
        violet: t("xiadown.common.colorOptions.violet", language),
        rose: t("xiadown.common.colorOptions.rose", language),
        red: t("xiadown.common.colorOptions.red", language),
        orange: t("xiadown.common.colorOptions.orange", language),
        amber: t("xiadown.common.colorOptions.amber", language),
        teal: t("xiadown.common.colorOptions.teal", language),
      },
      languages: {
        en: t("settings.language.option.en", language),
        zhCN: t("settings.language.option.zh-CN", language),
      },
    },
  };
}

type XiaText = ReturnType<typeof buildText>;

export function getXiaText(language?: string): XiaText {
  return buildText(isZhLanguage(language) ? "zh-CN" : "en");
}

export function isZhLanguage(language?: string) {
  return (language ?? "").toLowerCase().startsWith("zh");
}

export function resolveLibraryCoverFile(
  library?: LibraryDTO | null,
): LibraryFileDTO | null {
  const items = (library?.files ?? [])
    .filter(
      (file) =>
        (file.kind ?? "").trim().toLowerCase() === "thumbnail" &&
        !file.state.deleted,
    )
    .filter((file) => Boolean(file.storage.localPath?.trim()));
  return items[0] ?? null;
}

export function resolveLibraryCoverURL(
  baseURL: string,
  library?: LibraryDTO | null,
) {
  const path =
    resolveLibraryCoverFile(library)?.storage.localPath?.trim() ?? "";
  return buildAssetPreviewURL(baseURL, path);
}

export function isAudioLibraryFile(file?: LibraryFileDTO | null) {
  if (!file) {
    return false;
  }
  const kind = (file.kind ?? "").trim().toLowerCase();
  if (kind === "audio") {
    return true;
  }
  if (kind === "transcode") {
    return Boolean(file.media?.audioCodec || file.media?.channels);
  }
  const path = (file.storage.localPath ?? "").toLowerCase();
  return [
    ".aac",
    ".aif",
    ".aiff",
    ".alac",
    ".caf",
    ".flac",
    ".m4a",
    ".m4b",
    ".mp3",
    ".mp4",
    ".mpga",
    ".oga",
    ".ogg",
    ".opus",
    ".wav",
    ".wave",
    ".weba",
    ".webm",
  ].some((suffix) => path.endsWith(suffix));
}
