package service

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	appcookies "xiadown/internal/application/cookies"
	"xiadown/internal/domain/connectors"
)

type CookiesExportFormat string

const (
	CookiesExportTXT  CookiesExportFormat = "txt"
	CookiesExportJSON CookiesExportFormat = "json"
)

func (service *ConnectorsService) ExportConnectorCookies(ctx context.Context, id string, format CookiesExportFormat) (string, error) {
	trimmed := strings.TrimSpace(id)
	if trimmed == "" {
		return "", connectors.ErrInvalidConnector
	}
	connector, err := service.repo.Get(ctx, trimmed)
	if err != nil {
		return "", err
	}
	records := decodeCookies(connector.CookiesJSON)
	if len(records) == 0 {
		return "", connectors.ErrNoCookies
	}
	ext := strings.ToLower(strings.TrimSpace(string(format)))
	if ext == "" {
		ext = string(CookiesExportTXT)
	}
	if ext != string(CookiesExportTXT) && ext != string(CookiesExportJSON) {
		return "", connectors.ErrInvalidConnector
	}
	file, err := os.CreateTemp("", "xiadown-cookies-*."+ext)
	if err != nil {
		return "", err
	}
	path := file.Name()
	if err := file.Close(); err != nil {
		return "", err
	}
	if ext == string(CookiesExportJSON) {
		if err := writeJSONCookies(path, records); err != nil {
			return "", err
		}
	} else {
		if err := writeNetscapeCookies(path, records); err != nil {
			return "", err
		}
	}
	return path, nil
}

func writeJSONCookies(path string, cookies []appcookies.Record) error {
	data, err := json.MarshalIndent(cookies, "", "  ")
	if err != nil {
		return err
	}
	return writeFileAtomic(path, data, 0o600)
}

func writeNetscapeCookies(path string, cookies []appcookies.Record) error {
	builder := strings.Builder{}
	builder.WriteString("# Netscape HTTP Cookie File\n")
	builder.WriteString("# This file was generated by XiaDown.\n")

	for _, cookie := range cookies {
		domain := strings.TrimSpace(cookie.Domain)
		if domain == "" {
			continue
		}
		includeSubdomains := "FALSE"
		if strings.HasPrefix(domain, ".") {
			includeSubdomains = "TRUE"
		}
		secure := "FALSE"
		if cookie.Secure {
			secure = "TRUE"
		}
		pathValue := cookie.Path
		if strings.TrimSpace(pathValue) == "" {
			pathValue = "/"
		}
		expires := "0"
		if cookie.Expires > 0 {
			expires = strconv.FormatInt(cookie.Expires, 10)
		}
		builder.WriteString(strings.Join([]string{
			domain,
			includeSubdomains,
			pathValue,
			secure,
			expires,
			cookie.Name,
			cookie.Value,
		}, "\t"))
		builder.WriteString("\n")
	}

	return writeFileAtomic(path, []byte(builder.String()), 0o600)
}

func writeFileAtomic(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	tmp := filepath.Join(dir, "."+filepath.Base(path)+".tmp")
	if err := os.WriteFile(tmp, data, perm); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}
